/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.AdminFinanceData
import ai.hanzo.sdk.models.AdminFinanceCost
import ai.hanzo.sdk.models.AdminFinanceDerived
import ai.hanzo.sdk.models.AdminFinanceRevenue
import ai.hanzo.sdk.models.AdminSourceStatus

class AdminFinanceDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AdminFinanceData
        //val modelInstance = AdminFinanceData()

        // to test the property `cost`
        should("test cost") {
            // uncomment below to test the property
            //modelInstance.cost shouldBe ("TODO")
        }

        // to test the property `revenue`
        should("test revenue") {
            // uncomment below to test the property
            //modelInstance.revenue shouldBe ("TODO")
        }

        // to test the property `derived`
        should("test derived") {
            // uncomment below to test the property
            //modelInstance.derived shouldBe ("TODO")
        }

        // to test the property `generatedAt`
        should("test generatedAt") {
            // uncomment below to test the property
            //modelInstance.generatedAt shouldBe ("TODO")
        }

        // to test the property `sources`
        should("test sources") {
            // uncomment below to test the property
            //modelInstance.sources shouldBe ("TODO")
        }

    }
}
