/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.AffiliatesAdminAffiliateEnvelopeData
import ai.hanzo.sdk.models.AffiliatesAdminAffiliateView

class AffiliatesAdminAffiliateEnvelopeDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AffiliatesAdminAffiliateEnvelopeData
        //val modelInstance = AffiliatesAdminAffiliateEnvelopeData()

        // to test the property `affiliate`
        should("test affiliate") {
            // uncomment below to test the property
            //modelInstance.affiliate shouldBe ("TODO")
        }

    }
}
