/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.AgentsMetricsView
import ai.hanzo.sdk.models.AgentsResourceUsage
import ai.hanzo.sdk.models.AgentsSeriesLine

class AgentsMetricsViewTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AgentsMetricsView
        //val modelInstance = AgentsMetricsView()

        // to test the property `range`
        should("test range") {
            // uncomment below to test the property
            //modelInstance.range shouldBe ("TODO")
        }

        // to test the property `series`
        should("test series") {
            // uncomment below to test the property
            //modelInstance.series shouldBe ("TODO")
        }

        // to test the property `resource`
        should("test resource") {
            // uncomment below to test the property
            //modelInstance.resource shouldBe ("TODO")
        }

    }
}
