/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.AuthorsConnectResponse

class AuthorsConnectResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthorsConnectResponse
        //val modelInstance = AuthorsConnectResponse()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `githubLogin`
        should("test githubLogin") {
            // uncomment below to test the property
            //modelInstance.githubLogin shouldBe ("TODO")
        }

        // to test the property `verified`
        should("test verified") {
            // uncomment below to test the property
            //modelInstance.verified shouldBe ("TODO")
        }

        // to test the property `verifyCode`
        should("test verifyCode") {
            // uncomment below to test the property
            //modelInstance.verifyCode shouldBe ("TODO")
        }

        // to test the property `verifyFile`
        should("test verifyFile") {
            // uncomment below to test the property
            //modelInstance.verifyFile shouldBe ("TODO")
        }

        // to test the property `verifySnippet`
        should("test verifySnippet") {
            // uncomment below to test the property
            //modelInstance.verifySnippet shouldBe ("TODO")
        }

        // to test the property `shareBps`
        should("test shareBps") {
            // uncomment below to test the property
            //modelInstance.shareBps shouldBe ("TODO")
        }

        // to test the property `created`
        should("test created") {
            // uncomment below to test the property
            //modelInstance.created shouldBe ("TODO")
        }

    }
}
