/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.AutoUpsertAiProviderRequest

class AutoUpsertAiProviderRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AutoUpsertAiProviderRequest
        //val modelInstance = AutoUpsertAiProviderRequest()

        // to test the property `provider`
        should("test provider") {
            // uncomment below to test the property
            //modelInstance.provider shouldBe ("TODO")
        }

        // to test the property `baseUrl`
        should("test baseUrl") {
            // uncomment below to test the property
            //modelInstance.baseUrl shouldBe ("TODO")
        }

        // to test the property `apiKey`
        should("test apiKey") {
            // uncomment below to test the property
            //modelInstance.apiKey shouldBe ("TODO")
        }

    }
}
