/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.ChatGetShare200Response

class ChatGetShare200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChatGetShare200Response
        //val modelInstance = ChatGetShare200Response()

        // to test the property `links`
        should("test links") {
            // uncomment below to test the property
            //modelInstance.links shouldBe ("TODO")
        }

        // to test the property `nextCursor`
        should("test nextCursor") {
            // uncomment below to test the property
            //modelInstance.nextCursor shouldBe ("TODO")
        }

        // to test the property `hasNextPage`
        should("test hasNextPage") {
            // uncomment below to test the property
            //modelInstance.hasNextPage shouldBe ("TODO")
        }

    }
}
