/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.FrameworkInstallModule200Response

class FrameworkInstallModule200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FrameworkInstallModule200Response
        //val modelInstance = FrameworkInstallModule200Response()

        // to test the property `module`
        should("test module") {
            // uncomment below to test the property
            //modelInstance.module shouldBe ("TODO")
        }

        // to test the property `created`
        should("test created") {
            // uncomment below to test the property
            //modelInstance.created shouldBe ("TODO")
        }

        // to test the property `existing`
        should("test existing") {
            // uncomment below to test the property
            //modelInstance.existing shouldBe ("TODO")
        }

    }
}
