/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.FunctionsCreateFunctionRequest

class FunctionsCreateFunctionRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FunctionsCreateFunctionRequest
        //val modelInstance = FunctionsCreateFunctionRequest()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `environment`
        should("test environment") {
            // uncomment below to test the property
            //modelInstance.environment shouldBe ("TODO")
        }

        // to test the property `runtime`
        should("test runtime") {
            // uncomment below to test the property
            //modelInstance.runtime shouldBe ("TODO")
        }

        // to test the property `namespace`
        should("test namespace") {
            // uncomment below to test the property
            //modelInstance.namespace shouldBe ("TODO")
        }

        // to test the property `image`
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `code`
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `handler`
        should("test handler") {
            // uncomment below to test the property
            //modelInstance.handler shouldBe ("TODO")
        }

        // to test the property `timeoutSec`
        should("test timeoutSec") {
            // uncomment below to test the property
            //modelInstance.timeoutSec shouldBe ("TODO")
        }

        // to test the property `memoryLimit`
        should("test memoryLimit") {
            // uncomment below to test the property
            //modelInstance.memoryLimit shouldBe ("TODO")
        }

        // to test the property `envNames`
        should("test envNames") {
            // uncomment below to test the property
            //modelInstance.envNames shouldBe ("TODO")
        }

    }
}
