/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.GuardSanitizeConfigPii

class GuardSanitizeConfigPiiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GuardSanitizeConfigPii
        //val modelInstance = GuardSanitizeConfigPii()

        // to test the property `enabled`
        should("test enabled") {
            // uncomment below to test the property
            //modelInstance.enabled shouldBe ("TODO")
        }

        // to test the property `detectSsn`
        should("test detectSsn") {
            // uncomment below to test the property
            //modelInstance.detectSsn shouldBe ("TODO")
        }

        // to test the property `detectCreditCard`
        should("test detectCreditCard") {
            // uncomment below to test the property
            //modelInstance.detectCreditCard shouldBe ("TODO")
        }

        // to test the property `detectEmail`
        should("test detectEmail") {
            // uncomment below to test the property
            //modelInstance.detectEmail shouldBe ("TODO")
        }

        // to test the property `detectPhone`
        should("test detectPhone") {
            // uncomment below to test the property
            //modelInstance.detectPhone shouldBe ("TODO")
        }

        // to test the property `detectIp`
        should("test detectIp") {
            // uncomment below to test the property
            //modelInstance.detectIp shouldBe ("TODO")
        }

        // to test the property `detectApiKeys`
        should("test detectApiKeys") {
            // uncomment below to test the property
            //modelInstance.detectApiKeys shouldBe ("TODO")
        }

        // to test the property `redactionFormat`
        should("test redactionFormat") {
            // uncomment below to test the property
            //modelInstance.redactionFormat shouldBe ("TODO")
        }

    }
}
