/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.GuardSanitizeResultRedactionsInner

class GuardSanitizeResultRedactionsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GuardSanitizeResultRedactionsInner
        //val modelInstance = GuardSanitizeResultRedactionsInner()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `start`
        should("test start") {
            // uncomment below to test the property
            //modelInstance.start shouldBe ("TODO")
        }

        // to test the property `end`
        should("test end") {
            // uncomment below to test the property
            //modelInstance.end shouldBe ("TODO")
        }

        // to test the property `hash` - SHA-256 hash of the original value for audit correlation
        should("test hash") {
            // uncomment below to test the property
            //modelInstance.hash shouldBe ("TODO")
        }

    }
}
