/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.KmsListSecretSyncs200Response
import ai.hanzo.sdk.models.KmsSecretSync

class KmsListSecretSyncs200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of KmsListSecretSyncs200Response
        //val modelInstance = KmsListSecretSyncs200Response()

        // to test the property `secretSyncs`
        should("test secretSyncs") {
            // uncomment below to test the property
            //modelInstance.secretSyncs shouldBe ("TODO")
        }

    }
}
