/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.MqObjectInfo

class MqObjectInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MqObjectInfo
        //val modelInstance = MqObjectInfo()

        // to test the property `name` - Object name.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description` - Optional description.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `propertySize` - Object size in bytes.
        should("test propertySize") {
            // uncomment below to test the property
            //modelInstance.propertySize shouldBe ("TODO")
        }

        // to test the property `chunks` - Number of chunks.
        should("test chunks") {
            // uncomment below to test the property
            //modelInstance.chunks shouldBe ("TODO")
        }

        // to test the property `digest` - SHA-256 digest of the object.
        should("test digest") {
            // uncomment below to test the property
            //modelInstance.digest shouldBe ("TODO")
        }

        // to test the property `modified` - Last modification timestamp.
        should("test modified") {
            // uncomment below to test the property
            //modelInstance.modified shouldBe ("TODO")
        }

        // to test the property `deleted` - True if the object has been deleted.
        should("test deleted") {
            // uncomment below to test the property
            //modelInstance.deleted shouldBe ("TODO")
        }

        // to test the property `headers` - Optional metadata headers.
        should("test headers") {
            // uncomment below to test the property
            //modelInstance.headers shouldBe ("TODO")
        }

    }
}
