/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.O11yPrometheusResponse
import ai.hanzo.sdk.models.O11yPrometheusResponseData

class O11yPrometheusResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of O11yPrometheusResponse
        //val modelInstance = O11yPrometheusResponse()

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `errorType`
        should("test errorType") {
            // uncomment below to test the property
            //modelInstance.errorType shouldBe ("TODO")
        }

        // to test the property `error`
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

    }
}
