/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.PaasContainerRepo

class PaasContainerRepoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaasContainerRepo
        //val modelInstance = PaasContainerRepo()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `branch`
        should("test branch") {
            // uncomment below to test the property
            //modelInstance.branch shouldBe ("TODO")
        }

        // to test the property `connected`
        should("test connected") {
            // uncomment below to test the property
            //modelInstance.connected shouldBe ("TODO")
        }

    }
}
