/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.PlatformApplicationSaveBitbucketProviderRequestJson

class PlatformApplicationSaveBitbucketProviderRequestJsonTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlatformApplicationSaveBitbucketProviderRequestJson
        //val modelInstance = PlatformApplicationSaveBitbucketProviderRequestJson()

        // to test the property `applicationId`
        should("test applicationId") {
            // uncomment below to test the property
            //modelInstance.applicationId shouldBe ("TODO")
        }

        // to test the property `bitbucketRepository`
        should("test bitbucketRepository") {
            // uncomment below to test the property
            //modelInstance.bitbucketRepository shouldBe ("TODO")
        }

        // to test the property `bitbucketOwner`
        should("test bitbucketOwner") {
            // uncomment below to test the property
            //modelInstance.bitbucketOwner shouldBe ("TODO")
        }

        // to test the property `bitbucketBranch`
        should("test bitbucketBranch") {
            // uncomment below to test the property
            //modelInstance.bitbucketBranch shouldBe ("TODO")
        }

        // to test the property `bitbucketBuildPath`
        should("test bitbucketBuildPath") {
            // uncomment below to test the property
            //modelInstance.bitbucketBuildPath shouldBe ("TODO")
        }

        // to test the property `bitbucketId`
        should("test bitbucketId") {
            // uncomment below to test the property
            //modelInstance.bitbucketId shouldBe ("TODO")
        }

    }
}
