/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.PlatformCancelDeploymentJobApplication

class PlatformCancelDeploymentJobApplicationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlatformCancelDeploymentJobApplication
        //val modelInstance = PlatformCancelDeploymentJobApplication()

        // to test the property `applicationId`
        should("test applicationId") {
            // uncomment below to test the property
            //modelInstance.applicationId shouldBe ("TODO")
        }

        // to test the property `applicationType`
        should("test applicationType") {
            // uncomment below to test the property
            //modelInstance.applicationType shouldBe ("TODO")
        }

    }
}
