/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.PlatformApplicationSaveGithubProviderRequestJson

class PlatformApplicationSaveGithubProviderRequestJsonTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlatformApplicationSaveGithubProviderRequestJson
        //val modelInstance = PlatformApplicationSaveGithubProviderRequestJson()

        // to test the property `applicationId`
        should("test applicationId") {
            // uncomment below to test the property
            //modelInstance.applicationId shouldBe ("TODO")
        }

        // to test the property `repository`
        should("test repository") {
            // uncomment below to test the property
            //modelInstance.repository shouldBe ("TODO")
        }

        // to test the property `branch`
        should("test branch") {
            // uncomment below to test the property
            //modelInstance.branch shouldBe ("TODO")
        }

        // to test the property `owner`
        should("test owner") {
            // uncomment below to test the property
            //modelInstance.owner shouldBe ("TODO")
        }

        // to test the property `buildPath`
        should("test buildPath") {
            // uncomment below to test the property
            //modelInstance.buildPath shouldBe ("TODO")
        }

        // to test the property `githubId`
        should("test githubId") {
            // uncomment below to test the property
            //modelInstance.githubId shouldBe ("TODO")
        }

        // to test the property `watchPaths`
        should("test watchPaths") {
            // uncomment below to test the property
            //modelInstance.watchPaths shouldBe ("TODO")
        }

        // to test the property `triggerType`
        should("test triggerType") {
            // uncomment below to test the property
            //modelInstance.triggerType shouldBe ("TODO")
        }

        // to test the property `enableSubmodules`
        should("test enableSubmodules") {
            // uncomment below to test the property
            //modelInstance.enableSubmodules shouldBe ("TODO")
        }

    }
}
