/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.ReferralsMyReferralsResponse
import ai.hanzo.sdk.models.ReferralsMyReferralView
import ai.hanzo.sdk.models.ReferralsStatusCounts

class ReferralsMyReferralsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReferralsMyReferralsResponse
        //val modelInstance = ReferralsMyReferralsResponse()

        // to test the property `code` - The caller org's stable referral code.
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `link` - The share link, `<linkBase>/?ref=<code>`.
        should("test link") {
            // uncomment below to test the property
            //modelInstance.link shouldBe ("TODO")
        }

        // to test the property `referrerBonusCents` - Bonus granted to the referrer on qualification (1000 = $10).
        should("test referrerBonusCents") {
            // uncomment below to test the property
            //modelInstance.referrerBonusCents shouldBe ("TODO")
        }

        // to test the property `refereeBonusCents` - Bonus granted to the referee on qualification (500 = $5).
        should("test refereeBonusCents") {
            // uncomment below to test the property
            //modelInstance.refereeBonusCents shouldBe ("TODO")
        }

        // to test the property `creditsEarnedCents` - Total credit earned across all of the caller's referrals.
        should("test creditsEarnedCents") {
            // uncomment below to test the property
            //modelInstance.creditsEarnedCents shouldBe ("TODO")
        }

        // to test the property `counts`
        should("test counts") {
            // uncomment below to test the property
            //modelInstance.counts shouldBe ("TODO")
        }

        // to test the property `referrals`
        should("test referrals") {
            // uncomment below to test the property
            //modelInstance.referrals shouldBe ("TODO")
        }

    }
}
