/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.SearchMultiSearchResultsResultsInner

class SearchMultiSearchResultsResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SearchMultiSearchResultsResultsInner
        //val modelInstance = SearchMultiSearchResultsResultsInner()

        // to test the property `indexUid`
        should("test indexUid") {
            // uncomment below to test the property
            //modelInstance.indexUid shouldBe ("TODO")
        }

        // to test the property `hits`
        should("test hits") {
            // uncomment below to test the property
            //modelInstance.hits shouldBe ("TODO")
        }

        // to test the property `query`
        should("test query") {
            // uncomment below to test the property
            //modelInstance.query shouldBe ("TODO")
        }

        // to test the property `processingTimeMs`
        should("test processingTimeMs") {
            // uncomment below to test the property
            //modelInstance.processingTimeMs shouldBe ("TODO")
        }

        // to test the property `limit`
        should("test limit") {
            // uncomment below to test the property
            //modelInstance.limit shouldBe ("TODO")
        }

        // to test the property `offset`
        should("test offset") {
            // uncomment below to test the property
            //modelInstance.offset shouldBe ("TODO")
        }

        // to test the property `estimatedTotalHits`
        should("test estimatedTotalHits") {
            // uncomment below to test the property
            //modelInstance.estimatedTotalHits shouldBe ("TODO")
        }

    }
}
