/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.models.VectorRecommendPointsRequest
import ai.hanzo.sdk.models.VectorDeletePointsRequestPointsInner
import ai.hanzo.sdk.models.VectorFilter

class VectorRecommendPointsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of VectorRecommendPointsRequest
        //val modelInstance = VectorRecommendPointsRequest()

        // to test the property `positive`
        should("test positive") {
            // uncomment below to test the property
            //modelInstance.positive shouldBe ("TODO")
        }

        // to test the property `negative`
        should("test negative") {
            // uncomment below to test the property
            //modelInstance.negative shouldBe ("TODO")
        }

        // to test the property `filter`
        should("test filter") {
            // uncomment below to test the property
            //modelInstance.filter shouldBe ("TODO")
        }

        // to test the property `limit`
        should("test limit") {
            // uncomment below to test the property
            //modelInstance.limit shouldBe ("TODO")
        }

        // to test the property `withPayload`
        should("test withPayload") {
            // uncomment below to test the property
            //modelInstance.withPayload shouldBe ("TODO")
        }

        // to test the property `withVector`
        should("test withVector") {
            // uncomment below to test the property
            //modelInstance.withVector shouldBe ("TODO")
        }

    }
}
