/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.apis.FlowRunsApi
import ai.hanzo.sdk.models.AutoFlowRun
import ai.hanzo.sdk.models.AutoListFlowRuns200Response
import ai.hanzo.sdk.models.FlowBulkCancelFlowRunsRequest
import ai.hanzo.sdk.models.FlowFlowRun
import ai.hanzo.sdk.models.FlowListFlowRuns200Response
import ai.hanzo.sdk.models.FlowRetryFlowRunRequest

class FlowRunsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FlowRunsApi
        //val apiInstance = FlowRunsApi()

        // to test autoGetFlowRun
        should("test autoGetFlowRun") {
            // uncomment below to test autoGetFlowRun
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : AutoFlowRun = apiInstance.autoGetFlowRun(id)
            //result shouldBe ("TODO")
        }

        // to test autoListFlowRuns
        should("test autoListFlowRuns") {
            // uncomment below to test autoListFlowRuns
            //val flowId : kotlin.String = flowId_example // kotlin.String | 
            //val status : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val createdAfter : java.time.OffsetDateTime = 2013-10-20T19:20:30+01:00 // java.time.OffsetDateTime | 
            //val createdBefore : java.time.OffsetDateTime = 2013-10-20T19:20:30+01:00 // java.time.OffsetDateTime | 
            //val result : AutoListFlowRuns200Response = apiInstance.autoListFlowRuns(flowId, status, cursor, limit, createdAfter, createdBefore)
            //result shouldBe ("TODO")
        }

        // to test autoResumeFlowRun
        should("test autoResumeFlowRun") {
            // uncomment below to test autoResumeFlowRun
            //val id : kotlin.String = id_example // kotlin.String | 
            //val requestId : kotlin.String = requestId_example // kotlin.String | 
            //val body : kotlin.Any = Object // kotlin.Any | 
            //val result : kotlin.Any = apiInstance.autoResumeFlowRun(id, requestId, body)
            //result shouldBe ("TODO")
        }

        // to test autoRetryFlowRun
        should("test autoRetryFlowRun") {
            // uncomment below to test autoRetryFlowRun
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.autoRetryFlowRun(id)
            //result shouldBe ("TODO")
        }

        // to test flowBulkCancelFlowRuns
        should("test flowBulkCancelFlowRuns") {
            // uncomment below to test flowBulkCancelFlowRuns
            //val flowBulkCancelFlowRunsRequest : FlowBulkCancelFlowRunsRequest =  // FlowBulkCancelFlowRunsRequest | 
            //val result : kotlin.Any = apiInstance.flowBulkCancelFlowRuns(flowBulkCancelFlowRunsRequest)
            //result shouldBe ("TODO")
        }

        // to test flowGetFlowRun
        should("test flowGetFlowRun") {
            // uncomment below to test flowGetFlowRun
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : FlowFlowRun = apiInstance.flowGetFlowRun(id)
            //result shouldBe ("TODO")
        }

        // to test flowListFlowRuns
        should("test flowListFlowRuns") {
            // uncomment below to test flowListFlowRuns
            //val flowId : kotlin.String = flowId_example // kotlin.String | 
            //val status : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | 
            //val tags : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val createdAfter : java.time.OffsetDateTime = 2013-10-20T19:20:30+01:00 // java.time.OffsetDateTime | 
            //val createdBefore : java.time.OffsetDateTime = 2013-10-20T19:20:30+01:00 // java.time.OffsetDateTime | 
            //val result : FlowListFlowRuns200Response = apiInstance.flowListFlowRuns(flowId, status, tags, cursor, limit, createdAfter, createdBefore)
            //result shouldBe ("TODO")
        }

        // to test flowResumeFlowRun
        should("test flowResumeFlowRun") {
            // uncomment below to test flowResumeFlowRun
            //val id : kotlin.String = id_example // kotlin.String | 
            //val requestId : kotlin.String = requestId_example // kotlin.String | 
            //val body : kotlin.Any = Object // kotlin.Any | 
            //val result : kotlin.Any = apiInstance.flowResumeFlowRun(id, requestId, body)
            //result shouldBe ("TODO")
        }

        // to test flowRetryFlowRun
        should("test flowRetryFlowRun") {
            // uncomment below to test flowRetryFlowRun
            //val id : kotlin.String = id_example // kotlin.String | 
            //val flowRetryFlowRunRequest : FlowRetryFlowRunRequest =  // FlowRetryFlowRunRequest | 
            //val result : FlowFlowRun = apiInstance.flowRetryFlowRun(id, flowRetryFlowRunRequest)
            //result shouldBe ("TODO")
        }

    }
}
