/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.apis.GitProviderApi
import ai.hanzo.sdk.models.PlatformTRPCResult

class GitProviderApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GitProviderApi
        //val apiInstance = GitProviderApi()

        // to test platformGitProviderGetAll
        should("test platformGitProviderGetAll") {
            // uncomment below to test platformGitProviderGetAll
            //val result : PlatformTRPCResult = apiInstance.platformGitProviderGetAll()
            //result shouldBe ("TODO")
        }

    }
}
