/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.apis.LoadBalancersApi
import ai.hanzo.sdk.models.DoListLoadBalancers200Response
import ai.hanzo.sdk.models.DoLoadBalancer
import ai.hanzo.sdk.models.DoLoadBalancerCreate
import ai.hanzo.sdk.models.InlineObject

class LoadBalancersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LoadBalancersApi
        //val apiInstance = LoadBalancersApi()

        // to test doCreateLoadBalancer
        should("test doCreateLoadBalancer") {
            // uncomment below to test doCreateLoadBalancer
            //val doLoadBalancerCreate : DoLoadBalancerCreate =  // DoLoadBalancerCreate | 
            //val result : DoLoadBalancer = apiInstance.doCreateLoadBalancer(doLoadBalancerCreate)
            //result shouldBe ("TODO")
        }

        // to test doDeleteLoadBalancer
        should("test doDeleteLoadBalancer") {
            // uncomment below to test doDeleteLoadBalancer
            //val id : kotlin.String = id_example // kotlin.String | DO load balancer id
            //apiInstance.doDeleteLoadBalancer(id)
        }

        // to test doGetLoadBalancer
        should("test doGetLoadBalancer") {
            // uncomment below to test doGetLoadBalancer
            //val id : kotlin.String = id_example // kotlin.String | DO load balancer id
            //val result : DoLoadBalancer = apiInstance.doGetLoadBalancer(id)
            //result shouldBe ("TODO")
        }

        // to test doListLoadBalancers
        should("test doListLoadBalancers") {
            // uncomment below to test doListLoadBalancers
            //val result : DoListLoadBalancers200Response = apiInstance.doListLoadBalancers()
            //result shouldBe ("TODO")
        }

    }
}
