/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.hanzo.sdk.apis.ReportsApi
import ai.hanzo.sdk.models.AnalyticsCreateReportRequest
import ai.hanzo.sdk.models.AnalyticsReport
import ai.hanzo.sdk.models.AnalyticsRunAttributionReportRequest
import ai.hanzo.sdk.models.AnalyticsRunFunnelReportRequest
import ai.hanzo.sdk.models.AnalyticsRunGoalsReportRequest
import ai.hanzo.sdk.models.AnalyticsRunInsightsReportRequest
import ai.hanzo.sdk.models.AnalyticsRunJourneyReportRequest
import ai.hanzo.sdk.models.AnalyticsRunRetentionReportRequest
import ai.hanzo.sdk.models.AnalyticsRunRevenueReportRequest
import ai.hanzo.sdk.models.AnalyticsRunUtmReportRequest

class ReportsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReportsApi
        //val apiInstance = ReportsApi()

        // to test analyticsCreateReport
        should("test analyticsCreateReport") {
            // uncomment below to test analyticsCreateReport
            //val analyticsCreateReportRequest : AnalyticsCreateReportRequest =  // AnalyticsCreateReportRequest | 
            //val result : AnalyticsReport = apiInstance.analyticsCreateReport(analyticsCreateReportRequest)
            //result shouldBe ("TODO")
        }

        // to test analyticsDeleteReport
        should("test analyticsDeleteReport") {
            // uncomment below to test analyticsDeleteReport
            //val reportId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : kotlin.Any = apiInstance.analyticsDeleteReport(reportId)
            //result shouldBe ("TODO")
        }

        // to test analyticsGetReport
        should("test analyticsGetReport") {
            // uncomment below to test analyticsGetReport
            //val reportId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : AnalyticsReport = apiInstance.analyticsGetReport(reportId)
            //result shouldBe ("TODO")
        }

        // to test analyticsGetRevenueValues
        should("test analyticsGetRevenueValues") {
            // uncomment below to test analyticsGetRevenueValues
            //val websiteId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val startDate : java.time.OffsetDateTime = 2013-10-20T19:20:30+01:00 // java.time.OffsetDateTime | 
            //val endDate : java.time.OffsetDateTime = 2013-10-20T19:20:30+01:00 // java.time.OffsetDateTime | 
            //val result : kotlin.collections.List<kotlin.Any> = apiInstance.analyticsGetRevenueValues(websiteId, startDate, endDate)
            //result shouldBe ("TODO")
        }

        // to test analyticsGetWebsiteReports
        should("test analyticsGetWebsiteReports") {
            // uncomment below to test analyticsGetWebsiteReports
            //val websiteId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val orderBy : kotlin.String = orderBy_example // kotlin.String | 
            //val search : kotlin.String = search_example // kotlin.String | 
            //val result : kotlin.collections.List<AnalyticsReport> = apiInstance.analyticsGetWebsiteReports(websiteId, page, pageSize, orderBy, search)
            //result shouldBe ("TODO")
        }

        // to test analyticsListReports
        should("test analyticsListReports") {
            // uncomment below to test analyticsListReports
            //val websiteId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val teamId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val orderBy : kotlin.String = orderBy_example // kotlin.String | 
            //val search : kotlin.String = search_example // kotlin.String | 
            //val result : kotlin.collections.List<AnalyticsReport> = apiInstance.analyticsListReports(websiteId, teamId, page, pageSize, orderBy, search)
            //result shouldBe ("TODO")
        }

        // to test analyticsRunAttributionReport
        should("test analyticsRunAttributionReport") {
            // uncomment below to test analyticsRunAttributionReport
            //val analyticsRunAttributionReportRequest : AnalyticsRunAttributionReportRequest =  // AnalyticsRunAttributionReportRequest | 
            //val result : kotlin.collections.List<kotlin.Any> = apiInstance.analyticsRunAttributionReport(analyticsRunAttributionReportRequest)
            //result shouldBe ("TODO")
        }

        // to test analyticsRunFunnelReport
        should("test analyticsRunFunnelReport") {
            // uncomment below to test analyticsRunFunnelReport
            //val analyticsRunFunnelReportRequest : AnalyticsRunFunnelReportRequest =  // AnalyticsRunFunnelReportRequest | 
            //val result : kotlin.collections.List<kotlin.Any> = apiInstance.analyticsRunFunnelReport(analyticsRunFunnelReportRequest)
            //result shouldBe ("TODO")
        }

        // to test analyticsRunGoalsReport
        should("test analyticsRunGoalsReport") {
            // uncomment below to test analyticsRunGoalsReport
            //val analyticsRunGoalsReportRequest : AnalyticsRunGoalsReportRequest =  // AnalyticsRunGoalsReportRequest | 
            //val result : kotlin.collections.List<kotlin.Any> = apiInstance.analyticsRunGoalsReport(analyticsRunGoalsReportRequest)
            //result shouldBe ("TODO")
        }

        // to test analyticsRunInsightsReport
        should("test analyticsRunInsightsReport") {
            // uncomment below to test analyticsRunInsightsReport
            //val analyticsRunInsightsReportRequest : AnalyticsRunInsightsReportRequest =  // AnalyticsRunInsightsReportRequest | 
            //val result : kotlin.collections.List<kotlin.Any> = apiInstance.analyticsRunInsightsReport(analyticsRunInsightsReportRequest)
            //result shouldBe ("TODO")
        }

        // to test analyticsRunJourneyReport
        should("test analyticsRunJourneyReport") {
            // uncomment below to test analyticsRunJourneyReport
            //val analyticsRunJourneyReportRequest : AnalyticsRunJourneyReportRequest =  // AnalyticsRunJourneyReportRequest | 
            //val result : kotlin.collections.List<kotlin.Any> = apiInstance.analyticsRunJourneyReport(analyticsRunJourneyReportRequest)
            //result shouldBe ("TODO")
        }

        // to test analyticsRunRetentionReport
        should("test analyticsRunRetentionReport") {
            // uncomment below to test analyticsRunRetentionReport
            //val analyticsRunRetentionReportRequest : AnalyticsRunRetentionReportRequest =  // AnalyticsRunRetentionReportRequest | 
            //val result : kotlin.collections.List<kotlin.Any> = apiInstance.analyticsRunRetentionReport(analyticsRunRetentionReportRequest)
            //result shouldBe ("TODO")
        }

        // to test analyticsRunRevenueReport
        should("test analyticsRunRevenueReport") {
            // uncomment below to test analyticsRunRevenueReport
            //val analyticsRunRevenueReportRequest : AnalyticsRunRevenueReportRequest =  // AnalyticsRunRevenueReportRequest | 
            //val result : kotlin.collections.List<kotlin.Any> = apiInstance.analyticsRunRevenueReport(analyticsRunRevenueReportRequest)
            //result shouldBe ("TODO")
        }

        // to test analyticsRunUtmReport
        should("test analyticsRunUtmReport") {
            // uncomment below to test analyticsRunUtmReport
            //val analyticsRunUtmReportRequest : AnalyticsRunUtmReportRequest =  // AnalyticsRunUtmReportRequest | 
            //val result : kotlin.collections.List<kotlin.Any> = apiInstance.analyticsRunUtmReport(analyticsRunUtmReportRequest)
            //result shouldBe ("TODO")
        }

        // to test analyticsUpdateReport
        should("test analyticsUpdateReport") {
            // uncomment below to test analyticsUpdateReport
            //val reportId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val analyticsCreateReportRequest : AnalyticsCreateReportRequest =  // AnalyticsCreateReportRequest | 
            //val result : AnalyticsReport = apiInstance.analyticsUpdateReport(reportId, analyticsCreateReportRequest)
            //result shouldBe ("TODO")
        }

    }
}
