/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.hanzo.sdk.models.DnsUpdateZoneRequest
import ai.hanzo.sdk.models.KmsCreateCertificateAuthority200Response
import ai.hanzo.sdk.models.KmsCreateCertificateAuthorityRequest

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import ai.hanzo.sdk.infrastructure.ApiClient
import ai.hanzo.sdk.infrastructure.ApiResponse
import ai.hanzo.sdk.infrastructure.ClientException
import ai.hanzo.sdk.infrastructure.ClientError
import ai.hanzo.sdk.infrastructure.ServerException
import ai.hanzo.sdk.infrastructure.ServerError
import ai.hanzo.sdk.infrastructure.MultiValueMap
import ai.hanzo.sdk.infrastructure.PartConfig
import ai.hanzo.sdk.infrastructure.RequestConfig
import ai.hanzo.sdk.infrastructure.RequestMethod
import ai.hanzo.sdk.infrastructure.ResponseType
import ai.hanzo.sdk.infrastructure.Success
import ai.hanzo.sdk.infrastructure.toMultiValue

open class CertificateAuthoritiesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.hanzo.ai")
        }
    }

    /**
     * POST /v1/kms/cert-manager/ca
     * Create a certificate authority
     * 
     * @param kmsCreateCertificateAuthorityRequest 
     * @return KmsCreateCertificateAuthority200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun kmsCreateCertificateAuthority(kmsCreateCertificateAuthorityRequest: KmsCreateCertificateAuthorityRequest) : KmsCreateCertificateAuthority200Response = withContext(Dispatchers.IO) {
        val localVarResponse = kmsCreateCertificateAuthorityWithHttpInfo(kmsCreateCertificateAuthorityRequest = kmsCreateCertificateAuthorityRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as KmsCreateCertificateAuthority200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/kms/cert-manager/ca
     * Create a certificate authority
     * 
     * @param kmsCreateCertificateAuthorityRequest 
     * @return ApiResponse<KmsCreateCertificateAuthority200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun kmsCreateCertificateAuthorityWithHttpInfo(kmsCreateCertificateAuthorityRequest: KmsCreateCertificateAuthorityRequest) : ApiResponse<KmsCreateCertificateAuthority200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = kmsCreateCertificateAuthorityRequestConfig(kmsCreateCertificateAuthorityRequest = kmsCreateCertificateAuthorityRequest)

        return@withContext request<KmsCreateCertificateAuthorityRequest, KmsCreateCertificateAuthority200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation kmsCreateCertificateAuthority
     *
     * @param kmsCreateCertificateAuthorityRequest 
     * @return RequestConfig
     */
    fun kmsCreateCertificateAuthorityRequestConfig(kmsCreateCertificateAuthorityRequest: KmsCreateCertificateAuthorityRequest) : RequestConfig<KmsCreateCertificateAuthorityRequest> {
        val localVariableBody = kmsCreateCertificateAuthorityRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/kms/cert-manager/ca",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/kms/cert-manager/ca/{caId}
     * Delete a certificate authority
     * 
     * @param caId 
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun kmsDeleteCertificateAuthority(caId: java.util.UUID) : kotlin.Any = withContext(Dispatchers.IO) {
        val localVarResponse = kmsDeleteCertificateAuthorityWithHttpInfo(caId = caId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/kms/cert-manager/ca/{caId}
     * Delete a certificate authority
     * 
     * @param caId 
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun kmsDeleteCertificateAuthorityWithHttpInfo(caId: java.util.UUID) : ApiResponse<kotlin.Any?> = withContext(Dispatchers.IO) {
        val localVariableConfig = kmsDeleteCertificateAuthorityRequestConfig(caId = caId)

        return@withContext request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation kmsDeleteCertificateAuthority
     *
     * @param caId 
     * @return RequestConfig
     */
    fun kmsDeleteCertificateAuthorityRequestConfig(caId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/kms/cert-manager/ca/{caId}".replace("{"+"caId"+"}", encodeURIComponent(caId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/kms/cert-manager/ca/{caId}
     * Get a certificate authority by ID
     * 
     * @param caId 
     * @return KmsCreateCertificateAuthority200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun kmsGetCertificateAuthority(caId: java.util.UUID) : KmsCreateCertificateAuthority200Response = withContext(Dispatchers.IO) {
        val localVarResponse = kmsGetCertificateAuthorityWithHttpInfo(caId = caId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as KmsCreateCertificateAuthority200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/kms/cert-manager/ca/{caId}
     * Get a certificate authority by ID
     * 
     * @param caId 
     * @return ApiResponse<KmsCreateCertificateAuthority200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun kmsGetCertificateAuthorityWithHttpInfo(caId: java.util.UUID) : ApiResponse<KmsCreateCertificateAuthority200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = kmsGetCertificateAuthorityRequestConfig(caId = caId)

        return@withContext request<Unit, KmsCreateCertificateAuthority200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation kmsGetCertificateAuthority
     *
     * @param caId 
     * @return RequestConfig
     */
    fun kmsGetCertificateAuthorityRequestConfig(caId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/kms/cert-manager/ca/{caId}".replace("{"+"caId"+"}", encodeURIComponent(caId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /v1/kms/cert-manager/ca/{caId}
     * Update a certificate authority
     * 
     * @param caId 
     * @param dnsUpdateZoneRequest 
     * @return KmsCreateCertificateAuthority200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun kmsUpdateCertificateAuthority(caId: java.util.UUID, dnsUpdateZoneRequest: DnsUpdateZoneRequest) : KmsCreateCertificateAuthority200Response = withContext(Dispatchers.IO) {
        val localVarResponse = kmsUpdateCertificateAuthorityWithHttpInfo(caId = caId, dnsUpdateZoneRequest = dnsUpdateZoneRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as KmsCreateCertificateAuthority200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /v1/kms/cert-manager/ca/{caId}
     * Update a certificate authority
     * 
     * @param caId 
     * @param dnsUpdateZoneRequest 
     * @return ApiResponse<KmsCreateCertificateAuthority200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun kmsUpdateCertificateAuthorityWithHttpInfo(caId: java.util.UUID, dnsUpdateZoneRequest: DnsUpdateZoneRequest) : ApiResponse<KmsCreateCertificateAuthority200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = kmsUpdateCertificateAuthorityRequestConfig(caId = caId, dnsUpdateZoneRequest = dnsUpdateZoneRequest)

        return@withContext request<DnsUpdateZoneRequest, KmsCreateCertificateAuthority200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation kmsUpdateCertificateAuthority
     *
     * @param caId 
     * @param dnsUpdateZoneRequest 
     * @return RequestConfig
     */
    fun kmsUpdateCertificateAuthorityRequestConfig(caId: java.util.UUID, dnsUpdateZoneRequest: DnsUpdateZoneRequest) : RequestConfig<DnsUpdateZoneRequest> {
        val localVariableBody = dnsUpdateZoneRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/kms/cert-manager/ca/{caId}".replace("{"+"caId"+"}", encodeURIComponent(caId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
