/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.hanzo.sdk.models.ConsoleCreateDatasetRequest
import ai.hanzo.sdk.models.ConsoleDataset
import ai.hanzo.sdk.models.ConsoleDeleteDatasetItem200Response
import ai.hanzo.sdk.models.ConsoleGetDatasetRun200Response
import ai.hanzo.sdk.models.ConsoleListDatasetRuns200Response
import ai.hanzo.sdk.models.ConsoleListDatasets200Response
import ai.hanzo.sdk.models.EvalsDataset
import ai.hanzo.sdk.models.EvalsDatasetCreate
import ai.hanzo.sdk.models.EvalsDatasetItem
import ai.hanzo.sdk.models.EvalsDatasetItemCreate
import ai.hanzo.sdk.models.InlineObject

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import ai.hanzo.sdk.infrastructure.ApiClient
import ai.hanzo.sdk.infrastructure.ApiResponse
import ai.hanzo.sdk.infrastructure.ClientException
import ai.hanzo.sdk.infrastructure.ClientError
import ai.hanzo.sdk.infrastructure.ServerException
import ai.hanzo.sdk.infrastructure.ServerError
import ai.hanzo.sdk.infrastructure.MultiValueMap
import ai.hanzo.sdk.infrastructure.PartConfig
import ai.hanzo.sdk.infrastructure.RequestConfig
import ai.hanzo.sdk.infrastructure.RequestMethod
import ai.hanzo.sdk.infrastructure.ResponseType
import ai.hanzo.sdk.infrastructure.Success
import ai.hanzo.sdk.infrastructure.toMultiValue

open class DatasetsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.hanzo.ai")
        }
    }

    /**
     * POST /v1/console/datasets
     * Create a dataset
     * 
     * @param consoleCreateDatasetRequest 
     * @return ConsoleDataset
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun consoleCreateDataset(consoleCreateDatasetRequest: ConsoleCreateDatasetRequest) : ConsoleDataset = withContext(Dispatchers.IO) {
        val localVarResponse = consoleCreateDatasetWithHttpInfo(consoleCreateDatasetRequest = consoleCreateDatasetRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConsoleDataset
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/console/datasets
     * Create a dataset
     * 
     * @param consoleCreateDatasetRequest 
     * @return ApiResponse<ConsoleDataset?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun consoleCreateDatasetWithHttpInfo(consoleCreateDatasetRequest: ConsoleCreateDatasetRequest) : ApiResponse<ConsoleDataset?> = withContext(Dispatchers.IO) {
        val localVariableConfig = consoleCreateDatasetRequestConfig(consoleCreateDatasetRequest = consoleCreateDatasetRequest)

        return@withContext request<ConsoleCreateDatasetRequest, ConsoleDataset>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation consoleCreateDataset
     *
     * @param consoleCreateDatasetRequest 
     * @return RequestConfig
     */
    fun consoleCreateDatasetRequestConfig(consoleCreateDatasetRequest: ConsoleCreateDatasetRequest) : RequestConfig<ConsoleCreateDatasetRequest> {
        val localVariableBody = consoleCreateDatasetRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/console/datasets",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/console/datasets/{datasetName}/runs/{runName}
     * Delete a dataset run and all its run items
     * 
     * @param datasetName 
     * @param runName 
     * @return ConsoleDeleteDatasetItem200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun consoleDeleteDatasetRun(datasetName: kotlin.String, runName: kotlin.String) : ConsoleDeleteDatasetItem200Response = withContext(Dispatchers.IO) {
        val localVarResponse = consoleDeleteDatasetRunWithHttpInfo(datasetName = datasetName, runName = runName)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConsoleDeleteDatasetItem200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/console/datasets/{datasetName}/runs/{runName}
     * Delete a dataset run and all its run items
     * 
     * @param datasetName 
     * @param runName 
     * @return ApiResponse<ConsoleDeleteDatasetItem200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun consoleDeleteDatasetRunWithHttpInfo(datasetName: kotlin.String, runName: kotlin.String) : ApiResponse<ConsoleDeleteDatasetItem200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = consoleDeleteDatasetRunRequestConfig(datasetName = datasetName, runName = runName)

        return@withContext request<Unit, ConsoleDeleteDatasetItem200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation consoleDeleteDatasetRun
     *
     * @param datasetName 
     * @param runName 
     * @return RequestConfig
     */
    fun consoleDeleteDatasetRunRequestConfig(datasetName: kotlin.String, runName: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/console/datasets/{datasetName}/runs/{runName}".replace("{"+"datasetName"+"}", encodeURIComponent(datasetName.toString())).replace("{"+"runName"+"}", encodeURIComponent(runName.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/console/datasets/{datasetName}
     * Get a dataset by name
     * 
     * @param datasetName 
     * @return ConsoleDataset
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun consoleGetDataset(datasetName: kotlin.String) : ConsoleDataset = withContext(Dispatchers.IO) {
        val localVarResponse = consoleGetDatasetWithHttpInfo(datasetName = datasetName)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConsoleDataset
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/console/datasets/{datasetName}
     * Get a dataset by name
     * 
     * @param datasetName 
     * @return ApiResponse<ConsoleDataset?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun consoleGetDatasetWithHttpInfo(datasetName: kotlin.String) : ApiResponse<ConsoleDataset?> = withContext(Dispatchers.IO) {
        val localVariableConfig = consoleGetDatasetRequestConfig(datasetName = datasetName)

        return@withContext request<Unit, ConsoleDataset>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation consoleGetDataset
     *
     * @param datasetName 
     * @return RequestConfig
     */
    fun consoleGetDatasetRequestConfig(datasetName: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/console/datasets/{datasetName}".replace("{"+"datasetName"+"}", encodeURIComponent(datasetName.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/console/datasets/{datasetName}/runs/{runName}
     * Get a dataset run and its items
     * 
     * @param datasetName 
     * @param runName 
     * @return ConsoleGetDatasetRun200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun consoleGetDatasetRun(datasetName: kotlin.String, runName: kotlin.String) : ConsoleGetDatasetRun200Response = withContext(Dispatchers.IO) {
        val localVarResponse = consoleGetDatasetRunWithHttpInfo(datasetName = datasetName, runName = runName)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConsoleGetDatasetRun200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/console/datasets/{datasetName}/runs/{runName}
     * Get a dataset run and its items
     * 
     * @param datasetName 
     * @param runName 
     * @return ApiResponse<ConsoleGetDatasetRun200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun consoleGetDatasetRunWithHttpInfo(datasetName: kotlin.String, runName: kotlin.String) : ApiResponse<ConsoleGetDatasetRun200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = consoleGetDatasetRunRequestConfig(datasetName = datasetName, runName = runName)

        return@withContext request<Unit, ConsoleGetDatasetRun200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation consoleGetDatasetRun
     *
     * @param datasetName 
     * @param runName 
     * @return RequestConfig
     */
    fun consoleGetDatasetRunRequestConfig(datasetName: kotlin.String, runName: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/console/datasets/{datasetName}/runs/{runName}".replace("{"+"datasetName"+"}", encodeURIComponent(datasetName.toString())).replace("{"+"runName"+"}", encodeURIComponent(runName.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/console/datasets/{datasetName}/runs
     * Get dataset runs
     * 
     * @param datasetName 
     * @param page  (optional)
     * @param limit  (optional)
     * @return ConsoleListDatasetRuns200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun consoleListDatasetRuns(datasetName: kotlin.String, page: kotlin.Int? = null, limit: kotlin.Int? = null) : ConsoleListDatasetRuns200Response = withContext(Dispatchers.IO) {
        val localVarResponse = consoleListDatasetRunsWithHttpInfo(datasetName = datasetName, page = page, limit = limit)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConsoleListDatasetRuns200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/console/datasets/{datasetName}/runs
     * Get dataset runs
     * 
     * @param datasetName 
     * @param page  (optional)
     * @param limit  (optional)
     * @return ApiResponse<ConsoleListDatasetRuns200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun consoleListDatasetRunsWithHttpInfo(datasetName: kotlin.String, page: kotlin.Int?, limit: kotlin.Int?) : ApiResponse<ConsoleListDatasetRuns200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = consoleListDatasetRunsRequestConfig(datasetName = datasetName, page = page, limit = limit)

        return@withContext request<Unit, ConsoleListDatasetRuns200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation consoleListDatasetRuns
     *
     * @param datasetName 
     * @param page  (optional)
     * @param limit  (optional)
     * @return RequestConfig
     */
    fun consoleListDatasetRunsRequestConfig(datasetName: kotlin.String, page: kotlin.Int?, limit: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/console/datasets/{datasetName}/runs".replace("{"+"datasetName"+"}", encodeURIComponent(datasetName.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/console/datasets
     * Get all datasets
     * 
     * @param page  (optional)
     * @param limit  (optional)
     * @return ConsoleListDatasets200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun consoleListDatasets(page: kotlin.Int? = null, limit: kotlin.Int? = null) : ConsoleListDatasets200Response = withContext(Dispatchers.IO) {
        val localVarResponse = consoleListDatasetsWithHttpInfo(page = page, limit = limit)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConsoleListDatasets200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/console/datasets
     * Get all datasets
     * 
     * @param page  (optional)
     * @param limit  (optional)
     * @return ApiResponse<ConsoleListDatasets200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun consoleListDatasetsWithHttpInfo(page: kotlin.Int?, limit: kotlin.Int?) : ApiResponse<ConsoleListDatasets200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = consoleListDatasetsRequestConfig(page = page, limit = limit)

        return@withContext request<Unit, ConsoleListDatasets200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation consoleListDatasets
     *
     * @param page  (optional)
     * @param limit  (optional)
     * @return RequestConfig
     */
    fun consoleListDatasetsRequestConfig(page: kotlin.Int?, limit: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/console/datasets",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/evals/dataset-items
     * Add an item (input + optional expected output) to a dataset
     * 
     * @param evalsDatasetItemCreate 
     * @return EvalsDatasetItem
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun evalsPostV1EvalsDatasetItems(evalsDatasetItemCreate: EvalsDatasetItemCreate) : EvalsDatasetItem = withContext(Dispatchers.IO) {
        val localVarResponse = evalsPostV1EvalsDatasetItemsWithHttpInfo(evalsDatasetItemCreate = evalsDatasetItemCreate)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as EvalsDatasetItem
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/evals/dataset-items
     * Add an item (input + optional expected output) to a dataset
     * 
     * @param evalsDatasetItemCreate 
     * @return ApiResponse<EvalsDatasetItem?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun evalsPostV1EvalsDatasetItemsWithHttpInfo(evalsDatasetItemCreate: EvalsDatasetItemCreate) : ApiResponse<EvalsDatasetItem?> = withContext(Dispatchers.IO) {
        val localVariableConfig = evalsPostV1EvalsDatasetItemsRequestConfig(evalsDatasetItemCreate = evalsDatasetItemCreate)

        return@withContext request<EvalsDatasetItemCreate, EvalsDatasetItem>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation evalsPostV1EvalsDatasetItems
     *
     * @param evalsDatasetItemCreate 
     * @return RequestConfig
     */
    fun evalsPostV1EvalsDatasetItemsRequestConfig(evalsDatasetItemCreate: EvalsDatasetItemCreate) : RequestConfig<EvalsDatasetItemCreate> {
        val localVariableBody = evalsDatasetItemCreate
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/evals/dataset-items",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/evals/datasets
     * Create a dataset
     * 
     * @param evalsDatasetCreate 
     * @return EvalsDataset
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun evalsPostV1EvalsDatasets(evalsDatasetCreate: EvalsDatasetCreate) : EvalsDataset = withContext(Dispatchers.IO) {
        val localVarResponse = evalsPostV1EvalsDatasetsWithHttpInfo(evalsDatasetCreate = evalsDatasetCreate)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as EvalsDataset
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/evals/datasets
     * Create a dataset
     * 
     * @param evalsDatasetCreate 
     * @return ApiResponse<EvalsDataset?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun evalsPostV1EvalsDatasetsWithHttpInfo(evalsDatasetCreate: EvalsDatasetCreate) : ApiResponse<EvalsDataset?> = withContext(Dispatchers.IO) {
        val localVariableConfig = evalsPostV1EvalsDatasetsRequestConfig(evalsDatasetCreate = evalsDatasetCreate)

        return@withContext request<EvalsDatasetCreate, EvalsDataset>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation evalsPostV1EvalsDatasets
     *
     * @param evalsDatasetCreate 
     * @return RequestConfig
     */
    fun evalsPostV1EvalsDatasetsRequestConfig(evalsDatasetCreate: EvalsDatasetCreate) : RequestConfig<EvalsDatasetCreate> {
        val localVariableBody = evalsDatasetCreate
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/evals/datasets",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
