/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.hanzo.sdk.models.PlatformDockerRestartContainerRequest
import ai.hanzo.sdk.models.PlatformTRPCResult

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import ai.hanzo.sdk.infrastructure.ApiClient
import ai.hanzo.sdk.infrastructure.ApiResponse
import ai.hanzo.sdk.infrastructure.ClientException
import ai.hanzo.sdk.infrastructure.ClientError
import ai.hanzo.sdk.infrastructure.ServerException
import ai.hanzo.sdk.infrastructure.ServerError
import ai.hanzo.sdk.infrastructure.MultiValueMap
import ai.hanzo.sdk.infrastructure.PartConfig
import ai.hanzo.sdk.infrastructure.RequestConfig
import ai.hanzo.sdk.infrastructure.RequestMethod
import ai.hanzo.sdk.infrastructure.ResponseType
import ai.hanzo.sdk.infrastructure.Success
import ai.hanzo.sdk.infrastructure.toMultiValue

open class DockerApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.hanzo.ai")
        }
    }

    /**
     * GET /v1/platform/docker/getConfig
     * Get Docker inspect for a container
     * 
     * @param input URL-encoded JSON input for tRPC queries (optional)
     * @return PlatformTRPCResult
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun platformDockerGetConfig(input: kotlin.String? = null) : PlatformTRPCResult = withContext(Dispatchers.IO) {
        val localVarResponse = platformDockerGetConfigWithHttpInfo(input = input)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PlatformTRPCResult
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/platform/docker/getConfig
     * Get Docker inspect for a container
     * 
     * @param input URL-encoded JSON input for tRPC queries (optional)
     * @return ApiResponse<PlatformTRPCResult?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun platformDockerGetConfigWithHttpInfo(input: kotlin.String?) : ApiResponse<PlatformTRPCResult?> = withContext(Dispatchers.IO) {
        val localVariableConfig = platformDockerGetConfigRequestConfig(input = input)

        return@withContext request<Unit, PlatformTRPCResult>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation platformDockerGetConfig
     *
     * @param input URL-encoded JSON input for tRPC queries (optional)
     * @return RequestConfig
     */
    fun platformDockerGetConfigRequestConfig(input: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (input != null) {
                    put("input", listOf(input.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/platform/docker/getConfig",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/platform/docker/getContainers
     * List all Docker containers
     * 
     * @param input URL-encoded JSON input for tRPC queries (optional)
     * @return PlatformTRPCResult
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun platformDockerGetContainers(input: kotlin.String? = null) : PlatformTRPCResult = withContext(Dispatchers.IO) {
        val localVarResponse = platformDockerGetContainersWithHttpInfo(input = input)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PlatformTRPCResult
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/platform/docker/getContainers
     * List all Docker containers
     * 
     * @param input URL-encoded JSON input for tRPC queries (optional)
     * @return ApiResponse<PlatformTRPCResult?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun platformDockerGetContainersWithHttpInfo(input: kotlin.String?) : ApiResponse<PlatformTRPCResult?> = withContext(Dispatchers.IO) {
        val localVariableConfig = platformDockerGetContainersRequestConfig(input = input)

        return@withContext request<Unit, PlatformTRPCResult>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation platformDockerGetContainers
     *
     * @param input URL-encoded JSON input for tRPC queries (optional)
     * @return RequestConfig
     */
    fun platformDockerGetContainersRequestConfig(input: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (input != null) {
                    put("input", listOf(input.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/platform/docker/getContainers",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/platform/docker/restartContainer
     * Restart a container by ID
     * 
     * @param platformDockerRestartContainerRequest 
     * @return PlatformTRPCResult
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun platformDockerRestartContainer(platformDockerRestartContainerRequest: PlatformDockerRestartContainerRequest) : PlatformTRPCResult = withContext(Dispatchers.IO) {
        val localVarResponse = platformDockerRestartContainerWithHttpInfo(platformDockerRestartContainerRequest = platformDockerRestartContainerRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PlatformTRPCResult
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/platform/docker/restartContainer
     * Restart a container by ID
     * 
     * @param platformDockerRestartContainerRequest 
     * @return ApiResponse<PlatformTRPCResult?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun platformDockerRestartContainerWithHttpInfo(platformDockerRestartContainerRequest: PlatformDockerRestartContainerRequest) : ApiResponse<PlatformTRPCResult?> = withContext(Dispatchers.IO) {
        val localVariableConfig = platformDockerRestartContainerRequestConfig(platformDockerRestartContainerRequest = platformDockerRestartContainerRequest)

        return@withContext request<PlatformDockerRestartContainerRequest, PlatformTRPCResult>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation platformDockerRestartContainer
     *
     * @param platformDockerRestartContainerRequest 
     * @return RequestConfig
     */
    fun platformDockerRestartContainerRequestConfig(platformDockerRestartContainerRequest: PlatformDockerRestartContainerRequest) : RequestConfig<PlatformDockerRestartContainerRequest> {
        val localVariableBody = platformDockerRestartContainerRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/platform/docker/restartContainer",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
