/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.hanzo.sdk.models.BotGetIntegration200Response
import ai.hanzo.sdk.models.BotListIntegrations200Response
import ai.hanzo.sdk.models.KmsCreateIntegration200Response
import ai.hanzo.sdk.models.KmsCreateIntegrationRequest
import ai.hanzo.sdk.models.KmsUpdateIntegrationRequest

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import ai.hanzo.sdk.infrastructure.ApiClient
import ai.hanzo.sdk.infrastructure.ApiResponse
import ai.hanzo.sdk.infrastructure.ClientException
import ai.hanzo.sdk.infrastructure.ClientError
import ai.hanzo.sdk.infrastructure.ServerException
import ai.hanzo.sdk.infrastructure.ServerError
import ai.hanzo.sdk.infrastructure.MultiValueMap
import ai.hanzo.sdk.infrastructure.PartConfig
import ai.hanzo.sdk.infrastructure.RequestConfig
import ai.hanzo.sdk.infrastructure.RequestMethod
import ai.hanzo.sdk.infrastructure.ResponseType
import ai.hanzo.sdk.infrastructure.Success
import ai.hanzo.sdk.infrastructure.toMultiValue

open class IntegrationsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.hanzo.ai")
        }
    }

    /**
     * GET /v1/bot/integrations/{slug}
     * Get integration detail with latest version
     * 
     * @param slug 
     * @return BotGetIntegration200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun botGetIntegration(slug: kotlin.String) : BotGetIntegration200Response = withContext(Dispatchers.IO) {
        val localVarResponse = botGetIntegrationWithHttpInfo(slug = slug)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BotGetIntegration200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/bot/integrations/{slug}
     * Get integration detail with latest version
     * 
     * @param slug 
     * @return ApiResponse<BotGetIntegration200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun botGetIntegrationWithHttpInfo(slug: kotlin.String) : ApiResponse<BotGetIntegration200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = botGetIntegrationRequestConfig(slug = slug)

        return@withContext request<Unit, BotGetIntegration200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation botGetIntegration
     *
     * @param slug 
     * @return RequestConfig
     */
    fun botGetIntegrationRequestConfig(slug: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/bot/integrations/{slug}".replace("{"+"slug"+"}", encodeURIComponent(slug.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter sort
     */
     enum class SortBotListIntegrations(val value: kotlin.String) {
         @Json(name = "updated") updated("updated"),
         @Json(name = "downloads") downloads("downloads"),
         @Json(name = "name") name("name");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /v1/bot/integrations
     * List integrations (paginated)
     * 
     * @param sort  (optional, default to Sort.updated)
     * @param limit  (optional, default to 50)
     * @param cursor  (optional)
     * @return BotListIntegrations200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun botListIntegrations(sort: SortBotListIntegrations? = SortBotListIntegrations.updated, limit: kotlin.Int? = 50, cursor: java.time.OffsetDateTime? = null) : BotListIntegrations200Response = withContext(Dispatchers.IO) {
        val localVarResponse = botListIntegrationsWithHttpInfo(sort = sort, limit = limit, cursor = cursor)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BotListIntegrations200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/bot/integrations
     * List integrations (paginated)
     * 
     * @param sort  (optional, default to Sort.updated)
     * @param limit  (optional, default to 50)
     * @param cursor  (optional)
     * @return ApiResponse<BotListIntegrations200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun botListIntegrationsWithHttpInfo(sort: SortBotListIntegrations?, limit: kotlin.Int?, cursor: java.time.OffsetDateTime?) : ApiResponse<BotListIntegrations200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = botListIntegrationsRequestConfig(sort = sort, limit = limit, cursor = cursor)

        return@withContext request<Unit, BotListIntegrations200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation botListIntegrations
     *
     * @param sort  (optional, default to Sort.updated)
     * @param limit  (optional, default to 50)
     * @param cursor  (optional)
     * @return RequestConfig
     */
    fun botListIntegrationsRequestConfig(sort: SortBotListIntegrations?, limit: kotlin.Int?, cursor: java.time.OffsetDateTime?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (sort != null) {
                    put("sort", listOf(sort.value))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (cursor != null) {
                    put("cursor", listOf(parseDateToQueryString<java.time.OffsetDateTime>(cursor)))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/bot/integrations",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/kms/integration
     * Create an integration
     * 
     * @param kmsCreateIntegrationRequest 
     * @return KmsCreateIntegration200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun kmsCreateIntegration(kmsCreateIntegrationRequest: KmsCreateIntegrationRequest) : KmsCreateIntegration200Response = withContext(Dispatchers.IO) {
        val localVarResponse = kmsCreateIntegrationWithHttpInfo(kmsCreateIntegrationRequest = kmsCreateIntegrationRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as KmsCreateIntegration200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/kms/integration
     * Create an integration
     * 
     * @param kmsCreateIntegrationRequest 
     * @return ApiResponse<KmsCreateIntegration200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun kmsCreateIntegrationWithHttpInfo(kmsCreateIntegrationRequest: KmsCreateIntegrationRequest) : ApiResponse<KmsCreateIntegration200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = kmsCreateIntegrationRequestConfig(kmsCreateIntegrationRequest = kmsCreateIntegrationRequest)

        return@withContext request<KmsCreateIntegrationRequest, KmsCreateIntegration200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation kmsCreateIntegration
     *
     * @param kmsCreateIntegrationRequest 
     * @return RequestConfig
     */
    fun kmsCreateIntegrationRequestConfig(kmsCreateIntegrationRequest: KmsCreateIntegrationRequest) : RequestConfig<KmsCreateIntegrationRequest> {
        val localVariableBody = kmsCreateIntegrationRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/kms/integration",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/kms/integration/{integrationId}
     * Delete an integration
     * 
     * @param integrationId 
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun kmsDeleteIntegration(integrationId: java.util.UUID) : kotlin.Any = withContext(Dispatchers.IO) {
        val localVarResponse = kmsDeleteIntegrationWithHttpInfo(integrationId = integrationId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/kms/integration/{integrationId}
     * Delete an integration
     * 
     * @param integrationId 
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun kmsDeleteIntegrationWithHttpInfo(integrationId: java.util.UUID) : ApiResponse<kotlin.Any?> = withContext(Dispatchers.IO) {
        val localVariableConfig = kmsDeleteIntegrationRequestConfig(integrationId = integrationId)

        return@withContext request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation kmsDeleteIntegration
     *
     * @param integrationId 
     * @return RequestConfig
     */
    fun kmsDeleteIntegrationRequestConfig(integrationId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/kms/integration/{integrationId}".replace("{"+"integrationId"+"}", encodeURIComponent(integrationId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /v1/kms/integration/{integrationId}
     * Update an integration
     * 
     * @param integrationId 
     * @param kmsUpdateIntegrationRequest 
     * @return KmsCreateIntegration200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun kmsUpdateIntegration(integrationId: java.util.UUID, kmsUpdateIntegrationRequest: KmsUpdateIntegrationRequest) : KmsCreateIntegration200Response = withContext(Dispatchers.IO) {
        val localVarResponse = kmsUpdateIntegrationWithHttpInfo(integrationId = integrationId, kmsUpdateIntegrationRequest = kmsUpdateIntegrationRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as KmsCreateIntegration200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /v1/kms/integration/{integrationId}
     * Update an integration
     * 
     * @param integrationId 
     * @param kmsUpdateIntegrationRequest 
     * @return ApiResponse<KmsCreateIntegration200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun kmsUpdateIntegrationWithHttpInfo(integrationId: java.util.UUID, kmsUpdateIntegrationRequest: KmsUpdateIntegrationRequest) : ApiResponse<KmsCreateIntegration200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = kmsUpdateIntegrationRequestConfig(integrationId = integrationId, kmsUpdateIntegrationRequest = kmsUpdateIntegrationRequest)

        return@withContext request<KmsUpdateIntegrationRequest, KmsCreateIntegration200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation kmsUpdateIntegration
     *
     * @param integrationId 
     * @param kmsUpdateIntegrationRequest 
     * @return RequestConfig
     */
    fun kmsUpdateIntegrationRequestConfig(integrationId: java.util.UUID, kmsUpdateIntegrationRequest: KmsUpdateIntegrationRequest) : RequestConfig<KmsUpdateIntegrationRequest> {
        val localVariableBody = kmsUpdateIntegrationRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/kms/integration/{integrationId}".replace("{"+"integrationId"+"}", encodeURIComponent(integrationId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
