/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.hanzo.sdk.models.CloudObjectUsage

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import ai.hanzo.sdk.infrastructure.ApiClient
import ai.hanzo.sdk.infrastructure.ApiResponse
import ai.hanzo.sdk.infrastructure.ClientException
import ai.hanzo.sdk.infrastructure.ClientError
import ai.hanzo.sdk.infrastructure.ServerException
import ai.hanzo.sdk.infrastructure.ServerError
import ai.hanzo.sdk.infrastructure.MultiValueMap
import ai.hanzo.sdk.infrastructure.PartConfig
import ai.hanzo.sdk.infrastructure.RequestConfig
import ai.hanzo.sdk.infrastructure.RequestMethod
import ai.hanzo.sdk.infrastructure.ResponseType
import ai.hanzo.sdk.infrastructure.Success
import ai.hanzo.sdk.infrastructure.toMultiValue

open class UsageAPIApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.hanzo.ai")
        }
    }

    /**
     * GET /v1/cloud/get-range-usages
     * Api Controller Get Range Usages
     * get range usages
     * @param count count of range usages
     * @return kotlin.collections.List<CloudObjectUsage>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun cloudApiControllerGetRangeUsages(count: kotlin.String) : kotlin.collections.List<CloudObjectUsage> = withContext(Dispatchers.IO) {
        val localVarResponse = cloudApiControllerGetRangeUsagesWithHttpInfo(count = count)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<CloudObjectUsage>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/cloud/get-range-usages
     * Api Controller Get Range Usages
     * get range usages
     * @param count count of range usages
     * @return ApiResponse<kotlin.collections.List<CloudObjectUsage>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun cloudApiControllerGetRangeUsagesWithHttpInfo(count: kotlin.String) : ApiResponse<kotlin.collections.List<CloudObjectUsage>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = cloudApiControllerGetRangeUsagesRequestConfig(count = count)

        return@withContext request<Unit, kotlin.collections.List<CloudObjectUsage>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation cloudApiControllerGetRangeUsages
     *
     * @param count count of range usages
     * @return RequestConfig
     */
    fun cloudApiControllerGetRangeUsagesRequestConfig(count: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("count", listOf(count.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/cloud/get-range-usages",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/cloud/get-usages
     * Api Controller Get User Table Infos
     * get userTableInfos
     * @return kotlin.collections.List<CloudObjectUsage>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun cloudApiControllerGetUserTableInfos() : kotlin.collections.List<CloudObjectUsage> = withContext(Dispatchers.IO) {
        val localVarResponse = cloudApiControllerGetUserTableInfosWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<CloudObjectUsage>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/cloud/get-usages
     * Api Controller Get User Table Infos
     * get userTableInfos
     * @return ApiResponse<kotlin.collections.List<CloudObjectUsage>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun cloudApiControllerGetUserTableInfosWithHttpInfo() : ApiResponse<kotlin.collections.List<CloudObjectUsage>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = cloudApiControllerGetUserTableInfosRequestConfig()

        return@withContext request<Unit, kotlin.collections.List<CloudObjectUsage>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation cloudApiControllerGetUserTableInfos
     *
     * @return RequestConfig
     */
    fun cloudApiControllerGetUserTableInfosRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/cloud/get-usages",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/cloud/get-users
     * Api Controller Get Users
     * get users
     * @return kotlin.collections.List<kotlin.String>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun cloudApiControllerGetUsers() : kotlin.collections.List<kotlin.String> = withContext(Dispatchers.IO) {
        val localVarResponse = cloudApiControllerGetUsersWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<kotlin.String>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/cloud/get-users
     * Api Controller Get Users
     * get users
     * @return ApiResponse<kotlin.collections.List<kotlin.String>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun cloudApiControllerGetUsersWithHttpInfo() : ApiResponse<kotlin.collections.List<kotlin.String>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = cloudApiControllerGetUsersRequestConfig()

        return@withContext request<Unit, kotlin.collections.List<kotlin.String>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation cloudApiControllerGetUsers
     *
     * @return RequestConfig
     */
    fun cloudApiControllerGetUsersRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/cloud/get-users",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/nexus/get-range-usages
     * get Range Usages
     * Get range usages
     * @param count Count of range usages
     * @return kotlin.collections.List<CloudObjectUsage>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun nexusGetRangeUsages(count: kotlin.String) : kotlin.collections.List<CloudObjectUsage> = withContext(Dispatchers.IO) {
        val localVarResponse = nexusGetRangeUsagesWithHttpInfo(count = count)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<CloudObjectUsage>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/nexus/get-range-usages
     * get Range Usages
     * Get range usages
     * @param count Count of range usages
     * @return ApiResponse<kotlin.collections.List<CloudObjectUsage>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun nexusGetRangeUsagesWithHttpInfo(count: kotlin.String) : ApiResponse<kotlin.collections.List<CloudObjectUsage>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = nexusGetRangeUsagesRequestConfig(count = count)

        return@withContext request<Unit, kotlin.collections.List<CloudObjectUsage>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nexusGetRangeUsages
     *
     * @param count Count of range usages
     * @return RequestConfig
     */
    fun nexusGetRangeUsagesRequestConfig(count: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("count", listOf(count.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/nexus/get-range-usages",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/nexus/get-usages
     * get Usages
     * Get usage information
     * @return kotlin.collections.List<CloudObjectUsage>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun nexusGetUsages() : kotlin.collections.List<CloudObjectUsage> = withContext(Dispatchers.IO) {
        val localVarResponse = nexusGetUsagesWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<CloudObjectUsage>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/nexus/get-usages
     * get Usages
     * Get usage information
     * @return ApiResponse<kotlin.collections.List<CloudObjectUsage>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun nexusGetUsagesWithHttpInfo() : ApiResponse<kotlin.collections.List<CloudObjectUsage>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = nexusGetUsagesRequestConfig()

        return@withContext request<Unit, kotlin.collections.List<CloudObjectUsage>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nexusGetUsages
     *
     * @return RequestConfig
     */
    fun nexusGetUsagesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/nexus/get-usages",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/nexus/get-users
     * get Users
     * Get users
     * @return kotlin.collections.List<kotlin.String>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun nexusGetUsers() : kotlin.collections.List<kotlin.String> = withContext(Dispatchers.IO) {
        val localVarResponse = nexusGetUsersWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<kotlin.String>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/nexus/get-users
     * get Users
     * Get users
     * @return ApiResponse<kotlin.collections.List<kotlin.String>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun nexusGetUsersWithHttpInfo() : ApiResponse<kotlin.collections.List<kotlin.String>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = nexusGetUsersRequestConfig()

        return@withContext request<Unit, kotlin.collections.List<kotlin.String>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nexusGetUsers
     *
     * @return RequestConfig
     */
    fun nexusGetUsersRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/nexus/get-users",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
