/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.hanzo.sdk.models.IamControllersResponse
import ai.hanzo.sdk.models.IamObjectWebhook
import ai.hanzo.sdk.models.KmsCreateWebhook200Response
import ai.hanzo.sdk.models.KmsCreateWebhookRequest
import ai.hanzo.sdk.models.KmsListWebhooks200Response
import ai.hanzo.sdk.models.KmsUpdateWebhookRequest
import ai.hanzo.sdk.models.RegistryError
import ai.hanzo.sdk.models.RegistryWebhook
import ai.hanzo.sdk.models.RegistryWebhookCreate
import ai.hanzo.sdk.models.SearchWebhookResultsValue
import ai.hanzo.sdk.models.SearchWebhookSettingsValue

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import ai.hanzo.sdk.infrastructure.ApiClient
import ai.hanzo.sdk.infrastructure.ApiResponse
import ai.hanzo.sdk.infrastructure.ClientException
import ai.hanzo.sdk.infrastructure.ClientError
import ai.hanzo.sdk.infrastructure.ServerException
import ai.hanzo.sdk.infrastructure.ServerError
import ai.hanzo.sdk.infrastructure.MultiValueMap
import ai.hanzo.sdk.infrastructure.PartConfig
import ai.hanzo.sdk.infrastructure.RequestConfig
import ai.hanzo.sdk.infrastructure.RequestMethod
import ai.hanzo.sdk.infrastructure.ResponseType
import ai.hanzo.sdk.infrastructure.Success
import ai.hanzo.sdk.infrastructure.toMultiValue

open class WebhooksApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.hanzo.ai")
        }
    }

    /**
     * POST /v1/auto/webhooks/{flowId}
     * Receive incoming webhook for a flow trigger
     * 
     * @param flowId 
     * @param body  (optional)
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun autoHandleWebhook(flowId: kotlin.String, body: kotlin.Any? = null) : kotlin.Any = withContext(Dispatchers.IO) {
        val localVarResponse = autoHandleWebhookWithHttpInfo(flowId = flowId, body = body)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/auto/webhooks/{flowId}
     * Receive incoming webhook for a flow trigger
     * 
     * @param flowId 
     * @param body  (optional)
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun autoHandleWebhookWithHttpInfo(flowId: kotlin.String, body: kotlin.Any?) : ApiResponse<kotlin.Any?> = withContext(Dispatchers.IO) {
        val localVariableConfig = autoHandleWebhookRequestConfig(flowId = flowId, body = body)

        return@withContext request<kotlin.Any, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation autoHandleWebhook
     *
     * @param flowId 
     * @param body  (optional)
     * @return RequestConfig
     */
    fun autoHandleWebhookRequestConfig(flowId: kotlin.String, body: kotlin.Any?) : RequestConfig<kotlin.Any> {
        val localVariableBody = body
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/auto/webhooks/{flowId}".replace("{"+"flowId"+"}", encodeURIComponent(flowId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/auto/webhooks/{flowId}/sync
     * Receive webhook and wait for flow run result
     * 
     * @param flowId 
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun autoHandleWebhookSync(flowId: kotlin.String) : kotlin.Any = withContext(Dispatchers.IO) {
        val localVarResponse = autoHandleWebhookSyncWithHttpInfo(flowId = flowId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/auto/webhooks/{flowId}/sync
     * Receive webhook and wait for flow run result
     * 
     * @param flowId 
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun autoHandleWebhookSyncWithHttpInfo(flowId: kotlin.String) : ApiResponse<kotlin.Any?> = withContext(Dispatchers.IO) {
        val localVariableConfig = autoHandleWebhookSyncRequestConfig(flowId = flowId)

        return@withContext request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation autoHandleWebhookSync
     *
     * @param flowId 
     * @return RequestConfig
     */
    fun autoHandleWebhookSyncRequestConfig(flowId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/auto/webhooks/{flowId}/sync".replace("{"+"flowId"+"}", encodeURIComponent(flowId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/flow/webhooks/{flowId}
     * Receive incoming webhook for a flow trigger
     * 
     * @param flowId 
     * @param body  (optional)
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun flowHandleWebhook(flowId: kotlin.String, body: kotlin.Any? = null) : kotlin.Any = withContext(Dispatchers.IO) {
        val localVarResponse = flowHandleWebhookWithHttpInfo(flowId = flowId, body = body)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/flow/webhooks/{flowId}
     * Receive incoming webhook for a flow trigger
     * 
     * @param flowId 
     * @param body  (optional)
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun flowHandleWebhookWithHttpInfo(flowId: kotlin.String, body: kotlin.Any?) : ApiResponse<kotlin.Any?> = withContext(Dispatchers.IO) {
        val localVariableConfig = flowHandleWebhookRequestConfig(flowId = flowId, body = body)

        return@withContext request<kotlin.Any, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation flowHandleWebhook
     *
     * @param flowId 
     * @param body  (optional)
     * @return RequestConfig
     */
    fun flowHandleWebhookRequestConfig(flowId: kotlin.String, body: kotlin.Any?) : RequestConfig<kotlin.Any> {
        val localVariableBody = body
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/flow/webhooks/{flowId}".replace("{"+"flowId"+"}", encodeURIComponent(flowId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/flow/webhooks/{flowId}/sync
     * Receive webhook and wait for flow run result
     * 
     * @param flowId 
     * @param body  (optional)
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun flowHandleWebhookSync(flowId: kotlin.String, body: kotlin.Any? = null) : kotlin.Any = withContext(Dispatchers.IO) {
        val localVarResponse = flowHandleWebhookSyncWithHttpInfo(flowId = flowId, body = body)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/flow/webhooks/{flowId}/sync
     * Receive webhook and wait for flow run result
     * 
     * @param flowId 
     * @param body  (optional)
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun flowHandleWebhookSyncWithHttpInfo(flowId: kotlin.String, body: kotlin.Any?) : ApiResponse<kotlin.Any?> = withContext(Dispatchers.IO) {
        val localVariableConfig = flowHandleWebhookSyncRequestConfig(flowId = flowId, body = body)

        return@withContext request<kotlin.Any, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation flowHandleWebhookSync
     *
     * @param flowId 
     * @param body  (optional)
     * @return RequestConfig
     */
    fun flowHandleWebhookSyncRequestConfig(flowId: kotlin.String, body: kotlin.Any?) : RequestConfig<kotlin.Any> {
        val localVariableBody = body
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/flow/webhooks/{flowId}/sync".replace("{"+"flowId"+"}", encodeURIComponent(flowId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/flow/webhooks/{flowId}/simulate
     * Simulate a webhook to capture sample data
     * 
     * @param flowId 
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun flowSimulateWebhook(flowId: kotlin.String) : kotlin.Any = withContext(Dispatchers.IO) {
        val localVarResponse = flowSimulateWebhookWithHttpInfo(flowId = flowId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/flow/webhooks/{flowId}/simulate
     * Simulate a webhook to capture sample data
     * 
     * @param flowId 
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun flowSimulateWebhookWithHttpInfo(flowId: kotlin.String) : ApiResponse<kotlin.Any?> = withContext(Dispatchers.IO) {
        val localVariableConfig = flowSimulateWebhookRequestConfig(flowId = flowId)

        return@withContext request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation flowSimulateWebhook
     *
     * @param flowId 
     * @return RequestConfig
     */
    fun flowSimulateWebhookRequestConfig(flowId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/flow/webhooks/{flowId}/simulate".replace("{"+"flowId"+"}", encodeURIComponent(flowId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/iam/webhooks
     * Api Controller Add Webhook
     * add webhook
     * @param iamObjectWebhook The details of the webhook
     * @return IamControllersResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun iamApiControllerAddWebhook(iamObjectWebhook: IamObjectWebhook) : IamControllersResponse = withContext(Dispatchers.IO) {
        val localVarResponse = iamApiControllerAddWebhookWithHttpInfo(iamObjectWebhook = iamObjectWebhook)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamControllersResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/iam/webhooks
     * Api Controller Add Webhook
     * add webhook
     * @param iamObjectWebhook The details of the webhook
     * @return ApiResponse<IamControllersResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun iamApiControllerAddWebhookWithHttpInfo(iamObjectWebhook: IamObjectWebhook) : ApiResponse<IamControllersResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = iamApiControllerAddWebhookRequestConfig(iamObjectWebhook = iamObjectWebhook)

        return@withContext request<IamObjectWebhook, IamControllersResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation iamApiControllerAddWebhook
     *
     * @param iamObjectWebhook The details of the webhook
     * @return RequestConfig
     */
    fun iamApiControllerAddWebhookRequestConfig(iamObjectWebhook: IamObjectWebhook) : RequestConfig<IamObjectWebhook> {
        val localVariableBody = iamObjectWebhook
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/iam/webhooks",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/iam/webhooks/{id}
     * Api Controller Delete Webhook
     * delete webhook
     * @param id Resource identifier (owner/name)
     * @param iamObjectWebhook The details of the webhook
     * @return IamControllersResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun iamApiControllerDeleteWebhook(id: kotlin.String, iamObjectWebhook: IamObjectWebhook) : IamControllersResponse = withContext(Dispatchers.IO) {
        val localVarResponse = iamApiControllerDeleteWebhookWithHttpInfo(id = id, iamObjectWebhook = iamObjectWebhook)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamControllersResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/iam/webhooks/{id}
     * Api Controller Delete Webhook
     * delete webhook
     * @param id Resource identifier (owner/name)
     * @param iamObjectWebhook The details of the webhook
     * @return ApiResponse<IamControllersResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun iamApiControllerDeleteWebhookWithHttpInfo(id: kotlin.String, iamObjectWebhook: IamObjectWebhook) : ApiResponse<IamControllersResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = iamApiControllerDeleteWebhookRequestConfig(id = id, iamObjectWebhook = iamObjectWebhook)

        return@withContext request<IamObjectWebhook, IamControllersResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation iamApiControllerDeleteWebhook
     *
     * @param id Resource identifier (owner/name)
     * @param iamObjectWebhook The details of the webhook
     * @return RequestConfig
     */
    fun iamApiControllerDeleteWebhookRequestConfig(id: kotlin.String, iamObjectWebhook: IamObjectWebhook) : RequestConfig<IamObjectWebhook> {
        val localVariableBody = iamObjectWebhook
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/iam/webhooks/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/iam/webhooks/{id}
     * Api Controller Get Webhook
     * get webhook
     * @param id The id ( owner/name ) of the webhook (default to "built-in/admin")
     * @return IamObjectWebhook
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun iamApiControllerGetWebhook(id: kotlin.String = "built-in/admin") : IamObjectWebhook = withContext(Dispatchers.IO) {
        val localVarResponse = iamApiControllerGetWebhookWithHttpInfo(id = id)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamObjectWebhook
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/iam/webhooks/{id}
     * Api Controller Get Webhook
     * get webhook
     * @param id The id ( owner/name ) of the webhook (default to "built-in/admin")
     * @return ApiResponse<IamObjectWebhook?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun iamApiControllerGetWebhookWithHttpInfo(id: kotlin.String) : ApiResponse<IamObjectWebhook?> = withContext(Dispatchers.IO) {
        val localVariableConfig = iamApiControllerGetWebhookRequestConfig(id = id)

        return@withContext request<Unit, IamObjectWebhook>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation iamApiControllerGetWebhook
     *
     * @param id The id ( owner/name ) of the webhook (default to "built-in/admin")
     * @return RequestConfig
     */
    fun iamApiControllerGetWebhookRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/iam/webhooks/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/iam/webhooks
     * Api Controller Get Webhooks
     * get webhooks
     * @param owner The owner of webhooks (default to "built-in/admin")
     * @return kotlin.collections.List<IamObjectWebhook>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun iamApiControllerGetWebhooks(owner: kotlin.String = "built-in/admin") : kotlin.collections.List<IamObjectWebhook> = withContext(Dispatchers.IO) {
        val localVarResponse = iamApiControllerGetWebhooksWithHttpInfo(owner = owner)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<IamObjectWebhook>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/iam/webhooks
     * Api Controller Get Webhooks
     * get webhooks
     * @param owner The owner of webhooks (default to "built-in/admin")
     * @return ApiResponse<kotlin.collections.List<IamObjectWebhook>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun iamApiControllerGetWebhooksWithHttpInfo(owner: kotlin.String) : ApiResponse<kotlin.collections.List<IamObjectWebhook>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = iamApiControllerGetWebhooksRequestConfig(owner = owner)

        return@withContext request<Unit, kotlin.collections.List<IamObjectWebhook>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation iamApiControllerGetWebhooks
     *
     * @param owner The owner of webhooks (default to "built-in/admin")
     * @return RequestConfig
     */
    fun iamApiControllerGetWebhooksRequestConfig(owner: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("owner", listOf(owner.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/iam/webhooks",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /v1/iam/webhooks/{id}
     * Api Controller Update Webhook
     * update webhook
     * @param id The id ( owner/name ) of the webhook (default to "built-in/admin")
     * @param iamObjectWebhook The details of the webhook
     * @return IamControllersResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun iamApiControllerUpdateWebhook(id: kotlin.String = "built-in/admin", iamObjectWebhook: IamObjectWebhook) : IamControllersResponse = withContext(Dispatchers.IO) {
        val localVarResponse = iamApiControllerUpdateWebhookWithHttpInfo(id = id, iamObjectWebhook = iamObjectWebhook)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IamControllersResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /v1/iam/webhooks/{id}
     * Api Controller Update Webhook
     * update webhook
     * @param id The id ( owner/name ) of the webhook (default to "built-in/admin")
     * @param iamObjectWebhook The details of the webhook
     * @return ApiResponse<IamControllersResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun iamApiControllerUpdateWebhookWithHttpInfo(id: kotlin.String, iamObjectWebhook: IamObjectWebhook) : ApiResponse<IamControllersResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = iamApiControllerUpdateWebhookRequestConfig(id = id, iamObjectWebhook = iamObjectWebhook)

        return@withContext request<IamObjectWebhook, IamControllersResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation iamApiControllerUpdateWebhook
     *
     * @param id The id ( owner/name ) of the webhook (default to "built-in/admin")
     * @param iamObjectWebhook The details of the webhook
     * @return RequestConfig
     */
    fun iamApiControllerUpdateWebhookRequestConfig(id: kotlin.String, iamObjectWebhook: IamObjectWebhook) : RequestConfig<IamObjectWebhook> {
        val localVariableBody = iamObjectWebhook
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/v1/iam/webhooks/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/kms/webhooks
     * Create a webhook
     * 
     * @param kmsCreateWebhookRequest 
     * @return KmsCreateWebhook200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun kmsCreateWebhook(kmsCreateWebhookRequest: KmsCreateWebhookRequest) : KmsCreateWebhook200Response = withContext(Dispatchers.IO) {
        val localVarResponse = kmsCreateWebhookWithHttpInfo(kmsCreateWebhookRequest = kmsCreateWebhookRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as KmsCreateWebhook200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/kms/webhooks
     * Create a webhook
     * 
     * @param kmsCreateWebhookRequest 
     * @return ApiResponse<KmsCreateWebhook200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun kmsCreateWebhookWithHttpInfo(kmsCreateWebhookRequest: KmsCreateWebhookRequest) : ApiResponse<KmsCreateWebhook200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = kmsCreateWebhookRequestConfig(kmsCreateWebhookRequest = kmsCreateWebhookRequest)

        return@withContext request<KmsCreateWebhookRequest, KmsCreateWebhook200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation kmsCreateWebhook
     *
     * @param kmsCreateWebhookRequest 
     * @return RequestConfig
     */
    fun kmsCreateWebhookRequestConfig(kmsCreateWebhookRequest: KmsCreateWebhookRequest) : RequestConfig<KmsCreateWebhookRequest> {
        val localVariableBody = kmsCreateWebhookRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/kms/webhooks",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/kms/webhooks/{webhookId}
     * Delete a webhook
     * 
     * @param webhookId 
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun kmsDeleteWebhook(webhookId: java.util.UUID) : kotlin.Any = withContext(Dispatchers.IO) {
        val localVarResponse = kmsDeleteWebhookWithHttpInfo(webhookId = webhookId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/kms/webhooks/{webhookId}
     * Delete a webhook
     * 
     * @param webhookId 
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun kmsDeleteWebhookWithHttpInfo(webhookId: java.util.UUID) : ApiResponse<kotlin.Any?> = withContext(Dispatchers.IO) {
        val localVariableConfig = kmsDeleteWebhookRequestConfig(webhookId = webhookId)

        return@withContext request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation kmsDeleteWebhook
     *
     * @param webhookId 
     * @return RequestConfig
     */
    fun kmsDeleteWebhookRequestConfig(webhookId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/kms/webhooks/{webhookId}".replace("{"+"webhookId"+"}", encodeURIComponent(webhookId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/kms/webhooks
     * List webhooks for a project
     * 
     * @param workspaceId 
     * @return KmsListWebhooks200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun kmsListWebhooks(workspaceId: java.util.UUID) : KmsListWebhooks200Response = withContext(Dispatchers.IO) {
        val localVarResponse = kmsListWebhooksWithHttpInfo(workspaceId = workspaceId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as KmsListWebhooks200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/kms/webhooks
     * List webhooks for a project
     * 
     * @param workspaceId 
     * @return ApiResponse<KmsListWebhooks200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun kmsListWebhooksWithHttpInfo(workspaceId: java.util.UUID) : ApiResponse<KmsListWebhooks200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = kmsListWebhooksRequestConfig(workspaceId = workspaceId)

        return@withContext request<Unit, KmsListWebhooks200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation kmsListWebhooks
     *
     * @param workspaceId 
     * @return RequestConfig
     */
    fun kmsListWebhooksRequestConfig(workspaceId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("workspaceId", listOf(workspaceId.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/kms/webhooks",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/kms/webhooks/{webhookId}/test
     * Test a webhook
     * 
     * @param webhookId 
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun kmsTestWebhook(webhookId: java.util.UUID) : kotlin.Any = withContext(Dispatchers.IO) {
        val localVarResponse = kmsTestWebhookWithHttpInfo(webhookId = webhookId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/kms/webhooks/{webhookId}/test
     * Test a webhook
     * 
     * @param webhookId 
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun kmsTestWebhookWithHttpInfo(webhookId: java.util.UUID) : ApiResponse<kotlin.Any?> = withContext(Dispatchers.IO) {
        val localVariableConfig = kmsTestWebhookRequestConfig(webhookId = webhookId)

        return@withContext request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation kmsTestWebhook
     *
     * @param webhookId 
     * @return RequestConfig
     */
    fun kmsTestWebhookRequestConfig(webhookId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/kms/webhooks/{webhookId}/test".replace("{"+"webhookId"+"}", encodeURIComponent(webhookId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /v1/kms/webhooks/{webhookId}
     * Update a webhook
     * 
     * @param webhookId 
     * @param kmsUpdateWebhookRequest 
     * @return KmsCreateWebhook200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun kmsUpdateWebhook(webhookId: java.util.UUID, kmsUpdateWebhookRequest: KmsUpdateWebhookRequest) : KmsCreateWebhook200Response = withContext(Dispatchers.IO) {
        val localVarResponse = kmsUpdateWebhookWithHttpInfo(webhookId = webhookId, kmsUpdateWebhookRequest = kmsUpdateWebhookRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as KmsCreateWebhook200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /v1/kms/webhooks/{webhookId}
     * Update a webhook
     * 
     * @param webhookId 
     * @param kmsUpdateWebhookRequest 
     * @return ApiResponse<KmsCreateWebhook200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun kmsUpdateWebhookWithHttpInfo(webhookId: java.util.UUID, kmsUpdateWebhookRequest: KmsUpdateWebhookRequest) : ApiResponse<KmsCreateWebhook200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = kmsUpdateWebhookRequestConfig(webhookId = webhookId, kmsUpdateWebhookRequest = kmsUpdateWebhookRequest)

        return@withContext request<KmsUpdateWebhookRequest, KmsCreateWebhook200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation kmsUpdateWebhook
     *
     * @param webhookId 
     * @param kmsUpdateWebhookRequest 
     * @return RequestConfig
     */
    fun kmsUpdateWebhookRequestConfig(webhookId: java.util.UUID, kmsUpdateWebhookRequest: KmsUpdateWebhookRequest) : RequestConfig<KmsUpdateWebhookRequest> {
        val localVariableBody = kmsUpdateWebhookRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/kms/webhooks/{webhookId}".replace("{"+"webhookId"+"}", encodeURIComponent(webhookId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/registry/webhooks
     * Create webhook
     * 
     * @param registryWebhookCreate 
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun registryCreateWebhook(registryWebhookCreate: RegistryWebhookCreate) : kotlin.Any = withContext(Dispatchers.IO) {
        val localVarResponse = registryCreateWebhookWithHttpInfo(registryWebhookCreate = registryWebhookCreate)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/registry/webhooks
     * Create webhook
     * 
     * @param registryWebhookCreate 
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun registryCreateWebhookWithHttpInfo(registryWebhookCreate: RegistryWebhookCreate) : ApiResponse<kotlin.Any?> = withContext(Dispatchers.IO) {
        val localVariableConfig = registryCreateWebhookRequestConfig(registryWebhookCreate = registryWebhookCreate)

        return@withContext request<RegistryWebhookCreate, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation registryCreateWebhook
     *
     * @param registryWebhookCreate 
     * @return RequestConfig
     */
    fun registryCreateWebhookRequestConfig(registryWebhookCreate: RegistryWebhookCreate) : RequestConfig<RegistryWebhookCreate> {
        val localVariableBody = registryWebhookCreate
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/registry/webhooks",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/registry/webhooks/{id}
     * Delete webhook
     * 
     * @param id 
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun registryDeleteWebhook(id: kotlin.Int) : kotlin.Any = withContext(Dispatchers.IO) {
        val localVarResponse = registryDeleteWebhookWithHttpInfo(id = id)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/registry/webhooks/{id}
     * Delete webhook
     * 
     * @param id 
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun registryDeleteWebhookWithHttpInfo(id: kotlin.Int) : ApiResponse<kotlin.Any?> = withContext(Dispatchers.IO) {
        val localVariableConfig = registryDeleteWebhookRequestConfig(id = id)

        return@withContext request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation registryDeleteWebhook
     *
     * @param id 
     * @return RequestConfig
     */
    fun registryDeleteWebhookRequestConfig(id: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/registry/webhooks/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/registry/webhooks/{id}
     * Get webhook
     * 
     * @param id 
     * @return RegistryWebhook
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun registryGetWebhook(id: kotlin.Int) : RegistryWebhook = withContext(Dispatchers.IO) {
        val localVarResponse = registryGetWebhookWithHttpInfo(id = id)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RegistryWebhook
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/registry/webhooks/{id}
     * Get webhook
     * 
     * @param id 
     * @return ApiResponse<RegistryWebhook?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun registryGetWebhookWithHttpInfo(id: kotlin.Int) : ApiResponse<RegistryWebhook?> = withContext(Dispatchers.IO) {
        val localVariableConfig = registryGetWebhookRequestConfig(id = id)

        return@withContext request<Unit, RegistryWebhook>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation registryGetWebhook
     *
     * @param id 
     * @return RequestConfig
     */
    fun registryGetWebhookRequestConfig(id: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/registry/webhooks/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/registry/webhooks
     * List webhooks
     * 
     * @param projectId Filter by project ID (optional)
     * @param page  (optional, default to 1)
     * @param pageSize  (optional, default to 10)
     * @return kotlin.collections.List<RegistryWebhook>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun registryListWebhooks(projectId: kotlin.Int? = null, page: kotlin.Int? = 1, pageSize: kotlin.Int? = 10) : kotlin.collections.List<RegistryWebhook> = withContext(Dispatchers.IO) {
        val localVarResponse = registryListWebhooksWithHttpInfo(projectId = projectId, page = page, pageSize = pageSize)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<RegistryWebhook>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/registry/webhooks
     * List webhooks
     * 
     * @param projectId Filter by project ID (optional)
     * @param page  (optional, default to 1)
     * @param pageSize  (optional, default to 10)
     * @return ApiResponse<kotlin.collections.List<RegistryWebhook>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun registryListWebhooksWithHttpInfo(projectId: kotlin.Int?, page: kotlin.Int?, pageSize: kotlin.Int?) : ApiResponse<kotlin.collections.List<RegistryWebhook>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = registryListWebhooksRequestConfig(projectId = projectId, page = page, pageSize = pageSize)

        return@withContext request<Unit, kotlin.collections.List<RegistryWebhook>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation registryListWebhooks
     *
     * @param projectId Filter by project ID (optional)
     * @param page  (optional, default to 1)
     * @param pageSize  (optional, default to 10)
     * @return RequestConfig
     */
    fun registryListWebhooksRequestConfig(projectId: kotlin.Int?, page: kotlin.Int?, pageSize: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (projectId != null) {
                    put("project_id", listOf(projectId.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (pageSize != null) {
                    put("page_size", listOf(pageSize.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/registry/webhooks",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /v1/registry/webhooks/{id}
     * Update webhook
     * 
     * @param id 
     * @param registryWebhookCreate 
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun registryUpdateWebhook(id: kotlin.Int, registryWebhookCreate: RegistryWebhookCreate) : kotlin.Any = withContext(Dispatchers.IO) {
        val localVarResponse = registryUpdateWebhookWithHttpInfo(id = id, registryWebhookCreate = registryWebhookCreate)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /v1/registry/webhooks/{id}
     * Update webhook
     * 
     * @param id 
     * @param registryWebhookCreate 
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun registryUpdateWebhookWithHttpInfo(id: kotlin.Int, registryWebhookCreate: RegistryWebhookCreate) : ApiResponse<kotlin.Any?> = withContext(Dispatchers.IO) {
        val localVariableConfig = registryUpdateWebhookRequestConfig(id = id, registryWebhookCreate = registryWebhookCreate)

        return@withContext request<RegistryWebhookCreate, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation registryUpdateWebhook
     *
     * @param id 
     * @param registryWebhookCreate 
     * @return RequestConfig
     */
    fun registryUpdateWebhookRequestConfig(id: kotlin.Int, registryWebhookCreate: RegistryWebhookCreate) : RequestConfig<RegistryWebhookCreate> {
        val localVariableBody = registryWebhookCreate
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/v1/registry/webhooks/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/search/webhooks
     * Delete all webhooks
     * 
     * @return kotlin.collections.Map<kotlin.String, SearchWebhookResultsValue>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun searchDeleteWebhooks() : kotlin.collections.Map<kotlin.String, SearchWebhookResultsValue> = withContext(Dispatchers.IO) {
        val localVarResponse = searchDeleteWebhooksWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.Map<kotlin.String, SearchWebhookResultsValue>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/search/webhooks
     * Delete all webhooks
     * 
     * @return ApiResponse<kotlin.collections.Map<kotlin.String, SearchWebhookResultsValue>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun searchDeleteWebhooksWithHttpInfo() : ApiResponse<kotlin.collections.Map<kotlin.String, SearchWebhookResultsValue>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = searchDeleteWebhooksRequestConfig()

        return@withContext request<Unit, kotlin.collections.Map<kotlin.String, SearchWebhookResultsValue>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation searchDeleteWebhooks
     *
     * @return RequestConfig
     */
    fun searchDeleteWebhooksRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/search/webhooks",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/search/webhooks
     * Get webhook configuration
     * 
     * @return kotlin.collections.Map<kotlin.String, SearchWebhookResultsValue>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun searchGetWebhooks() : kotlin.collections.Map<kotlin.String, SearchWebhookResultsValue> = withContext(Dispatchers.IO) {
        val localVarResponse = searchGetWebhooksWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.Map<kotlin.String, SearchWebhookResultsValue>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/search/webhooks
     * Get webhook configuration
     * 
     * @return ApiResponse<kotlin.collections.Map<kotlin.String, SearchWebhookResultsValue>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun searchGetWebhooksWithHttpInfo() : ApiResponse<kotlin.collections.Map<kotlin.String, SearchWebhookResultsValue>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = searchGetWebhooksRequestConfig()

        return@withContext request<Unit, kotlin.collections.Map<kotlin.String, SearchWebhookResultsValue>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation searchGetWebhooks
     *
     * @return RequestConfig
     */
    fun searchGetWebhooksRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/search/webhooks",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /v1/search/webhooks
     * Update webhook configuration
     * 
     * @param requestBody 
     * @return kotlin.collections.Map<kotlin.String, SearchWebhookResultsValue>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun searchUpdateWebhooks(requestBody: kotlin.collections.Map<kotlin.String, SearchWebhookSettingsValue>) : kotlin.collections.Map<kotlin.String, SearchWebhookResultsValue> = withContext(Dispatchers.IO) {
        val localVarResponse = searchUpdateWebhooksWithHttpInfo(requestBody = requestBody)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.Map<kotlin.String, SearchWebhookResultsValue>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /v1/search/webhooks
     * Update webhook configuration
     * 
     * @param requestBody 
     * @return ApiResponse<kotlin.collections.Map<kotlin.String, SearchWebhookResultsValue>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun searchUpdateWebhooksWithHttpInfo(requestBody: kotlin.collections.Map<kotlin.String, SearchWebhookSettingsValue>) : ApiResponse<kotlin.collections.Map<kotlin.String, SearchWebhookResultsValue>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = searchUpdateWebhooksRequestConfig(requestBody = requestBody)

        return@withContext request<kotlin.collections.Map<kotlin.String, SearchWebhookSettingsValue>, kotlin.collections.Map<kotlin.String, SearchWebhookResultsValue>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation searchUpdateWebhooks
     *
     * @param requestBody 
     * @return RequestConfig
     */
    fun searchUpdateWebhooksRequestConfig(requestBody: kotlin.collections.Map<kotlin.String, SearchWebhookSettingsValue>) : RequestConfig<kotlin.collections.Map<kotlin.String, SearchWebhookSettingsValue>> {
        val localVariableBody = requestBody
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/search/webhooks",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
