/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import ai.hanzo.sdk.models.AdminProductRow

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status 
 * @param msg 
 * @param `data` 
 * @param data2 
 */


data class AdminAdminProducts200Response (

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "msg")
    val msg: kotlin.String? = null,

    @Json(name = "data")
    val `data`: kotlin.collections.List<AdminProductRow>? = null,

    @Json(name = "data2")
    val data2: kotlin.Int? = null

) {


}

