/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param kind 
 * @param agent Agent name.
 * @param message 
 * @param at 
 */


data class AgentsActivityView (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "kind")
    val kind: AgentsActivityView.Kind? = null,

    /* Agent name. */
    @Json(name = "agent")
    val agent: kotlin.String? = null,

    @Json(name = "message")
    val message: kotlin.String? = null,

    @Json(name = "at")
    val at: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: invoked,failed,created,updated
     */
    @JsonClass(generateAdapter = false)
    enum class Kind(val value: kotlin.String) {
        @Json(name = "invoked") invoked("invoked"),
        @Json(name = "failed") failed("failed"),
        @Json(name = "created") created("created"),
        @Json(name = "updated") updated("updated");
    }

}

