/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param agent 
 * @param actor 
 * @param status 
 * @param parentSessionId 
 * @param rootSessionId 
 * @param title 
 * @param taskWorkflowId 
 * @param taskRunId 
 * @param events 
 * @param children Direct fan-out count.
 * @param startedAt 
 * @param endedAt 
 * @param createdAt 
 * @param updatedAt 
 */


data class AgentsSessionView (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "agent")
    val agent: kotlin.String? = null,

    @Json(name = "actor")
    val actor: kotlin.String? = null,

    @Json(name = "status")
    val status: AgentsSessionView.Status? = null,

    @Json(name = "parentSessionId")
    val parentSessionId: kotlin.String? = null,

    @Json(name = "rootSessionId")
    val rootSessionId: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "taskWorkflowId")
    val taskWorkflowId: kotlin.String? = null,

    @Json(name = "taskRunId")
    val taskRunId: kotlin.String? = null,

    @Json(name = "events")
    val events: kotlin.Int? = null,

    /* Direct fan-out count. */
    @Json(name = "children")
    val children: kotlin.Int? = null,

    @Json(name = "startedAt")
    val startedAt: java.time.OffsetDateTime? = null,

    @Json(name = "endedAt")
    val endedAt: java.time.OffsetDateTime? = null,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: running,paused,done,error
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "running") running("running"),
        @Json(name = "paused") paused("paused"),
        @Json(name = "done") done("done"),
        @Json(name = "error") error("error");
    }

}

