/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `data` 
 * @param count 
 * @param page 
 * @param pageSize 
 */


data class AnalyticsPaginatedResponse (

    @Json(name = "data")
    val `data`: kotlin.collections.List<kotlin.Any?>? = null,

    @Json(name = "count")
    val count: kotlin.Int? = null,

    @Json(name = "page")
    val page: kotlin.Int? = null,

    @Json(name = "pageSize")
    val pageSize: kotlin.Int? = null

) {


}

