/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param projectSlug 
 * @param status 
 * @param source 
 * @param commit 
 * @param url 
 * @param createdAt 
 */


data class AppDeployment (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "projectSlug")
    val projectSlug: kotlin.String? = null,

    @Json(name = "status")
    val status: AppDeployment.Status? = null,

    @Json(name = "source")
    val source: AppDeployment.Source? = null,

    @Json(name = "commit")
    val commit: kotlin.String? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: queued,building,ready,error,canceled
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "queued") queued("queued"),
        @Json(name = "building") building("building"),
        @Json(name = "ready") ready("ready"),
        @Json(name = "error") error("error"),
        @Json(name = "canceled") canceled("canceled");
    }
    /**
     * 
     *
     * Values: tar,git
     */
    @JsonClass(generateAdapter = false)
    enum class Source(val value: kotlin.String) {
        @Json(name = "tar") tar("tar"),
        @Json(name = "git") git("git");
    }

}

