/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param displayName 
 * @param type 
 * @param required 
 * @param description 
 */


data class AutomationsPropSpec (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "displayName")
    val displayName: kotlin.String? = null,

    @Json(name = "type")
    val type: AutomationsPropSpec.Type? = null,

    @Json(name = "required")
    val required: kotlin.Boolean? = null,

    @Json(name = "description")
    val description: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: string,number,boolean,`object`,array
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "string") string("string"),
        @Json(name = "number") number("number"),
        @Json(name = "boolean") boolean("boolean"),
        @Json(name = "object") `object`("object"),
        @Json(name = "array") array("array");
    }

}

