/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param primaryColor 
 * @param logoIconUrl 
 * @param fullLogoUrl 
 * @param favIconUrl 
 * @param created 
 * @param updated 
 */


data class AutoPlatform (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "primaryColor")
    val primaryColor: kotlin.String? = null,

    @Json(name = "logoIconUrl")
    val logoIconUrl: kotlin.String? = null,

    @Json(name = "fullLogoUrl")
    val fullLogoUrl: kotlin.String? = null,

    @Json(name = "favIconUrl")
    val favIconUrl: kotlin.String? = null,

    @Json(name = "created")
    val created: java.time.OffsetDateTime? = null,

    @Json(name = "updated")
    val updated: java.time.OffsetDateTime? = null

) {


}

