/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param pluginKey 
 * @param action 
 * @param auth 
 */


data class ChatPostUserPluginsRequest (

    @Json(name = "pluginKey")
    val pluginKey: kotlin.String? = null,

    @Json(name = "action")
    val action: ChatPostUserPluginsRequest.Action? = null,

    @Json(name = "auth")
    val auth: kotlin.Any? = null

) {

    /**
     * 
     *
     * Values: install,uninstall
     */
    @JsonClass(generateAdapter = false)
    enum class Action(val value: kotlin.String) {
        @Json(name = "install") install("install"),
        @Json(name = "uninstall") uninstall("uninstall");
    }

}

