/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import ai.hanzo.sdk.models.CommerceBuyer
import ai.hanzo.sdk.models.CommercePaymentStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param orderId 
 * @param userId 
 * @param currency 
 * @param amount 
 * @param amountRefunded 
 * @param fee 
 * @param status 
 * @param captured 
 * @param live 
 * @param buyer 
 * @param metadata 
 * @param createdAt 
 * @param updatedAt 
 */


data class CommercePayment (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "orderId")
    val orderId: kotlin.String? = null,

    @Json(name = "userId")
    val userId: kotlin.String? = null,

    @Json(name = "currency")
    val currency: kotlin.String? = null,

    @Json(name = "amount")
    val amount: kotlin.Int? = null,

    @Json(name = "amountRefunded")
    val amountRefunded: kotlin.Int? = null,

    @Json(name = "fee")
    val fee: kotlin.Int? = null,

    @Json(name = "status")
    val status: CommercePaymentStatus? = null,

    @Json(name = "captured")
    val captured: kotlin.Boolean? = null,

    @Json(name = "live")
    val live: kotlin.Boolean? = null,

    @Json(name = "buyer")
    val buyer: CommerceBuyer? = null,

    @Json(name = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

) {


}

