/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import ai.hanzo.sdk.models.DidProfile

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param profiles 
 * @param total 
 * @param nextCursor 
 */


data class DidListProfiles200Response (

    @Json(name = "profiles")
    val profiles: kotlin.collections.List<DidProfile>? = null,

    @Json(name = "total")
    val total: kotlin.Int? = null,

    @Json(name = "next_cursor")
    val nextCursor: kotlin.String? = null

) {


}

