/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param enabled 
 * @param status 
 * @param algorithm 
 * @param dsRecord DS record to add at registrar
 * @param keyTag 
 * @param digestType 
 * @param digest 
 * @param publicKey 
 */


data class DnsDNSSECStatus (

    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = null,

    @Json(name = "status")
    val status: DnsDNSSECStatus.Status? = null,

    @Json(name = "algorithm")
    val algorithm: kotlin.String? = "ECDSAP256SHA256",

    /* DS record to add at registrar */
    @Json(name = "ds_record")
    val dsRecord: kotlin.String? = null,

    @Json(name = "key_tag")
    val keyTag: kotlin.Int? = null,

    @Json(name = "digest_type")
    val digestType: kotlin.String? = null,

    @Json(name = "digest")
    val digest: kotlin.String? = null,

    @Json(name = "public_key")
    val publicKey: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: active,pending,disabled
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "active") active("active"),
        @Json(name = "pending") pending("pending"),
        @Json(name = "disabled") disabled("disabled");
    }

}

