/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param environment 
 * @param runtime 
 * @param namespace 
 * @param image 
 * @param code 
 * @param handler 
 * @param timeoutSec 
 * @param memoryLimit 
 * @param envNames 
 */


data class FunctionsCreateFunctionRequest (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "environment")
    val environment: kotlin.String? = null,

    @Json(name = "runtime")
    val runtime: kotlin.String? = null,

    @Json(name = "namespace")
    val namespace: kotlin.String? = null,

    @Json(name = "image")
    val image: kotlin.String? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "handler")
    val handler: kotlin.String? = null,

    @Json(name = "timeoutSec")
    val timeoutSec: kotlin.Int? = null,

    @Json(name = "memoryLimit")
    val memoryLimit: kotlin.String? = null,

    @Json(name = "envNames")
    val envNames: kotlin.collections.List<kotlin.String>? = null

) {


}

