/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import ai.hanzo.sdk.models.GatewayChatMessageContent

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param role 
 * @param content 
 * @param name 
 * @param toolCalls 
 * @param toolCallId 
 */


data class GatewayChatMessage (

    @Json(name = "role")
    val role: GatewayChatMessage.Role,

    @Json(name = "content")
    val content: GatewayChatMessageContent,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "tool_calls")
    val toolCalls: kotlin.collections.List<kotlin.Any>? = null,

    @Json(name = "tool_call_id")
    val toolCallId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: system,user,assistant,tool
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "system") system("system"),
        @Json(name = "user") user("user"),
        @Json(name = "assistant") assistant("assistant"),
        @Json(name = "tool") tool("tool");
    }

}

