/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param inputCost 
 * @param outputCost 
 * @param totalCost 
 */


data class GatewayCalculateSpend200Response (

    @Json(name = "input_cost")
    val inputCost: java.math.BigDecimal? = null,

    @Json(name = "output_cost")
    val outputCost: java.math.BigDecimal? = null,

    @Json(name = "total_cost")
    val totalCost: java.math.BigDecimal? = null

) {


}

