/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param encryptedValue 
 * @param expiresAt 
 * @param expiresAfterViews 
 * @param accessType 
 * @param createdAt 
 */


data class KmsSharedSecret (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "encryptedValue")
    val encryptedValue: kotlin.String? = null,

    @Json(name = "expiresAt")
    val expiresAt: java.time.OffsetDateTime? = null,

    @Json(name = "expiresAfterViews")
    val expiresAfterViews: kotlin.Int? = null,

    @Json(name = "accessType")
    val accessType: KmsSharedSecret.AccessType? = null,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: anyone,organization
     */
    @JsonClass(generateAdapter = false)
    enum class AccessType(val value: kotlin.String) {
        @Json(name = "anyone") anyone("anyone"),
        @Json(name = "organization") organization("organization");
    }

}

