/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param direction 
 * @param count 
 */


data class KvListPopRequest (

    @Json(name = "direction")
    val direction: KvListPopRequest.Direction? = Direction.left,

    @Json(name = "count")
    val count: kotlin.Int? = 1

) {

    /**
     * 
     *
     * Values: left,right
     */
    @JsonClass(generateAdapter = false)
    enum class Direction(val value: kotlin.String) {
        @Json(name = "left") left("left"),
        @Json(name = "right") right("right");
    }

}

