/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `value` 
 * @param ttl TTL in seconds (omit for no expiry)
 * @param nx Only set if key does not exist
 * @param xx Only set if key already exists
 */


data class KvSetKeyRequest (

    @Json(name = "value")
    val `value`: kotlin.String,

    /* TTL in seconds (omit for no expiry) */
    @Json(name = "ttl")
    val ttl: kotlin.Int? = null,

    /* Only set if key does not exist */
    @Json(name = "nx")
    val nx: kotlin.Boolean? = null,

    /* Only set if key already exists */
    @Json(name = "xx")
    val xx: kotlin.Boolean? = null

) {


}

