/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A message stored in a JetStream stream.
 *
 * @param subject 
 * @param `data` 
 * @param headers 
 * @param sequence Stream sequence number.
 * @param timestamp 
 * @param numDelivered Number of times this message has been delivered.
 * @param numPending Messages remaining after this one (consumer context).
 */


data class MqStreamMessage (

    @Json(name = "subject")
    val subject: kotlin.String? = null,

    @Json(name = "data")
    val `data`: kotlin.String? = null,

    @Json(name = "headers")
    val headers: kotlin.collections.Map<kotlin.String, kotlin.collections.List<kotlin.String>>? = null,

    /* Stream sequence number. */
    @Json(name = "sequence")
    val sequence: kotlin.Int? = null,

    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime? = null,

    /* Number of times this message has been delivered. */
    @Json(name = "num_delivered")
    val numDelivered: kotlin.Int? = null,

    /* Messages remaining after this one (consumer context). */
    @Json(name = "num_pending")
    val numPending: kotlin.Int? = null

) {


}

