/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import ai.hanzo.sdk.models.O11yMetricPoint

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param requests 
 * @param errors 
 * @param latencyP50Ms 
 * @param latencyP95Ms 
 */


data class O11yMetricsResponseSeries (

    @Json(name = "requests")
    val requests: kotlin.collections.List<O11yMetricPoint>? = null,

    @Json(name = "errors")
    val errors: kotlin.collections.List<O11yMetricPoint>? = null,

    @Json(name = "latencyP50Ms")
    val latencyP50Ms: kotlin.collections.List<O11yMetricPoint>? = null,

    @Json(name = "latencyP95Ms")
    val latencyP95Ms: kotlin.collections.List<O11yMetricPoint>? = null

) {


}

