/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ts RFC3339 timestamp (UTC).
 * @param tsNano Nanosecond cursor.
 * @param severity INFO | WARN | ERROR | ...
 * @param body 
 * @param source \"infra\" (stdout) or \"request\" (org request log).
 */


data class ObserveLogLine (

    /* RFC3339 timestamp (UTC). */
    @Json(name = "ts")
    val ts: kotlin.String? = null,

    /* Nanosecond cursor. */
    @Json(name = "tsNano")
    val tsNano: kotlin.Long? = null,

    /* INFO | WARN | ERROR | ... */
    @Json(name = "severity")
    val severity: kotlin.String? = null,

    @Json(name = "body")
    val body: kotlin.String? = null,

    /* \"infra\" (stdout) or \"request\" (org request log). */
    @Json(name = "source")
    val source: ObserveLogLine.Source? = null

) {

    /**
     * \"infra\" (stdout) or \"request\" (org request log).
     *
     * Values: infra,request
     */
    @JsonClass(generateAdapter = false)
    enum class Source(val value: kotlin.String) {
        @Json(name = "infra") infra("infra"),
        @Json(name = "request") request("request");
    }

}

