/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import ai.hanzo.sdk.models.ProductDayCount

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Aggregate search statistics across all indexes.
 *
 * @param totalDocuments Total documents across all indexes.
 * @param totalSearches Always 0 — Meilisearch keeps no query-history counters.
 * @param totalSessions Always 0 — not derivable from the index.
 * @param searchesPerDay Always empty — no per-day query history is available.
 */


data class ProductSearchStats (

    /* Total documents across all indexes. */
    @Json(name = "totalDocuments")
    val totalDocuments: kotlin.Long,

    /* Always 0 — Meilisearch keeps no query-history counters. */
    @Json(name = "totalSearches")
    val totalSearches: kotlin.Long,

    /* Always 0 — not derivable from the index. */
    @Json(name = "totalSessions")
    val totalSessions: kotlin.Long,

    /* Always empty — no per-day query history is available. */
    @Json(name = "searchesPerDay")
    val searchesPerDay: kotlin.collections.List<ProductDayCount>

) {


}

