/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param type 
 * @param versions True version count
 * @param currentVersion 
 * @param createdAt 
 * @param lastUpdatedAt 
 */


data class PromptsPromptMetric (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    /* True version count */
    @Json(name = "versions")
    val versions: kotlin.Int? = null,

    @Json(name = "currentVersion")
    val currentVersion: kotlin.Int? = null,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "lastUpdatedAt")
    val lastUpdatedAt: java.time.OffsetDateTime? = null

) {


}

