/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param messages 
 * @param bytes 
 * @param firstSeq 
 * @param lastSeq 
 * @param consumerCount 
 */


data class PubsubStreamInfoState (

    @Json(name = "messages")
    val messages: kotlin.Int? = null,

    @Json(name = "bytes")
    val bytes: kotlin.Int? = null,

    @Json(name = "first_seq")
    val firstSeq: kotlin.Int? = null,

    @Json(name = "last_seq")
    val lastSeq: kotlin.Int? = null,

    @Json(name = "consumer_count")
    val consumerCount: kotlin.Int? = null

) {


}

