/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param maxValuesPerFacet 
 * @param sortFacetValuesBy 
 */


data class SearchSettingsFaceting (

    @Json(name = "maxValuesPerFacet")
    val maxValuesPerFacet: kotlin.Int? = null,

    @Json(name = "sortFacetValuesBy")
    val sortFacetValuesBy: SearchSettingsFaceting.SortFacetValuesBy? = null

) {

    /**
     * 
     *
     * Values: alpha,count
     */
    @JsonClass(generateAdapter = false)
    enum class SortFacetValuesBy(val value: kotlin.String) {
        @Json(name = "alpha") alpha("alpha"),
        @Json(name = "count") count("count");
    }

}

