/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param replicas 
 * @param storage 
 */


data class StreamBrokerInfoConfig (

    @Json(name = "replicas")
    val replicas: kotlin.Int? = null,

    @Json(name = "storage")
    val storage: StreamBrokerInfoConfig.Storage? = null

) {

    /**
     * 
     *
     * Values: file,memory
     */
    @JsonClass(generateAdapter = false)
    enum class Storage(val value: kotlin.String) {
        @Json(name = "file") file("file"),
        @Json(name = "memory") memory("memory");
    }

}

