/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param slug 
 * @param title 
 * @param category 
 * @param description 
 * @param framework 
 * @param features 
 * @param useCase 
 * @param tier Optional pricing tier
 * @param rating Optional gallery rating
 * @param source Live gallery fork/deploy URL
 * @param preview Live gallery screenshot/preview URL
 */


data class TemplatesTemplate (

    @Json(name = "slug")
    val slug: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "category")
    val category: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "framework")
    val framework: kotlin.String? = null,

    @Json(name = "features")
    val features: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "useCase")
    val useCase: kotlin.String? = null,

    /* Optional pricing tier */
    @Json(name = "tier")
    val tier: kotlin.Int? = null,

    /* Optional gallery rating */
    @Json(name = "rating")
    val rating: kotlin.Double? = null,

    /* Live gallery fork/deploy URL */
    @Json(name = "source")
    val source: kotlin.String? = null,

    /* Live gallery screenshot/preview URL */
    @Json(name = "preview")
    val preview: kotlin.String? = null

) {


}

