/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import ai.hanzo.sdk.models.VectorDeletePointsRequestPointsInner
import ai.hanzo.sdk.models.VectorScoredPointVector

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param version 
 * @param score 
 * @param payload 
 * @param vector 
 */


data class VectorScoredPoint (

    @Json(name = "id")
    val id: VectorDeletePointsRequestPointsInner? = null,

    @Json(name = "version")
    val version: kotlin.Int? = null,

    @Json(name = "score")
    val score: java.math.BigDecimal? = null,

    @Json(name = "payload")
    val payload: kotlin.Any? = null,

    @Json(name = "vector")
    val vector: VectorScoredPointVector? = null

) {


}

