/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.hanzo.sdk.models

import ai.hanzo.sdk.models.VectorCollectionConfigParams
import ai.hanzo.sdk.models.VectorHnswConfig
import ai.hanzo.sdk.models.VectorOptimizerConfig
import ai.hanzo.sdk.models.VectorWalConfig

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param params 
 * @param hnswConfig 
 * @param optimizerConfig 
 * @param walConfig 
 */


data class VectorCollectionConfig (

    @Json(name = "params")
    val params: VectorCollectionConfigParams? = null,

    @Json(name = "hnsw_config")
    val hnswConfig: VectorHnswConfig? = null,

    @Json(name = "optimizer_config")
    val optimizerConfig: VectorOptimizerConfig? = null,

    @Json(name = "wal_config")
    val walConfig: VectorWalConfig? = null

) {


}

